# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from typing import Any
from typing import Optional  # noqa: F401

from cloudtruth_api.flat import _environment as _e  # noqa: F401
from cloudtruth_api.flat import _logging as _l  # noqa: F401
from cloudtruth_api.flat import _requests as _r  # noqa: F401


def environments_create(
    name: str = None,  # The environment name. [required]
    description: Optional[str] = None,  # A description of the environment...
    parent: Optional[str] = None,  # Environments can inherit from a single parent environment which provides values for parameters when specific environment...
    _api_host: Optional[str] = None,  # API host, read from API_HOST if not provided
    _api_key: Optional[str] = None,  # API key for bearer auth, read from API_KEY if not provided
    _api_timeout: Optional[int] = None,  # timeout for operation, read from API_TIMEOUT if not provided, defaults to 5
    _log_level: Optional[str] = None,  # log level, read from API_LOG_LEVEL if not provided, defaults to info
) -> Any:
    # handler for environments_create: POST /api/v1/environments/
    _api_host = _api_host or _e.env_string("API_HOST", default="", except_missing=True)
    _api_key = _api_key or _e.env_string("API_KEY", except_missing=True)
    _api_timeout = _api_timeout or _e.env_int("API_TIMEOUT", default=5)
    _log_level = _log_level or _e.env_string("API_LOG_LEVEL", default="info")

    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "api/v1/environments/")

    params = {}
    body = {}
    body["name"] = name
    if description is not None:
        body["description"] = description
    if parent is not None:
        body["parent"] = parent

    data = _r.request("POST", url, headers=headers, params=params, body=body, timeout=_api_timeout)
    return data


def environments_destroy(
    id: str,  # A unique identifier for the environment. [required]
    _api_host: Optional[str] = None,  # API host, read from API_HOST if not provided
    _api_key: Optional[str] = None,  # API key for bearer auth, read from API_KEY if not provided
    _api_timeout: Optional[int] = None,  # timeout for operation, read from API_TIMEOUT if not provided, defaults to 5
    _log_level: Optional[str] = None,  # log level, read from API_LOG_LEVEL if not provided, defaults to info
) -> Any:
    # handler for environments_destroy: DELETE /api/v1/environments/{id}/
    _api_host = _api_host or _e.env_string("API_HOST", default="", except_missing=True)
    _api_key = _api_key or _e.env_string("API_KEY", except_missing=True)
    _api_timeout = _api_timeout or _e.env_int("API_TIMEOUT", default=5)
    _log_level = _log_level or _e.env_string("API_LOG_LEVEL", default="info")

    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "api/v1/environments", id)

    params = {}

    data = _r.request("DELETE", url, headers=headers, params=params, timeout=_api_timeout)
    return data


def environments_list(
    description__icontains: Optional[str] = None,
    name: Optional[str] = None,
    name__icontains: Optional[str] = None,
    ordering: Optional[str] = None,  # Which field to use when ordering the results.
    page: Optional[int] = None,  # A page number within the paginated result set.
    page_size: Optional[int] = None,  # Number of results to return per page.
    _api_host: Optional[str] = None,  # API host, read from API_HOST if not provided
    _api_key: Optional[str] = None,  # API key for bearer auth, read from API_KEY if not provided
    _api_timeout: Optional[int] = None,  # timeout for operation, read from API_TIMEOUT if not provided, defaults to 5
    _log_level: Optional[str] = None,  # log level, read from API_LOG_LEVEL if not provided, defaults to info
) -> Any:
    # handler for environments_list: GET /api/v1/environments/
    _api_host = _api_host or _e.env_string("API_HOST", default="", except_missing=True)
    _api_key = _api_key or _e.env_string("API_KEY", except_missing=True)
    _api_timeout = _api_timeout or _e.env_int("API_TIMEOUT", default=5)
    _log_level = _log_level or _e.env_string("API_LOG_LEVEL", default="info")

    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "api/v1/environments/")

    params = {}
    if description__icontains is not None:
        params["description__icontains"] = description__icontains
    if name is not None:
        params["name"] = name
    if name__icontains is not None:
        params["name__icontains"] = name__icontains
    if ordering is not None:
        params["ordering"] = ordering
    if page is not None:
        params["page"] = page
    if page_size is not None:
        params["page_size"] = page_size

    data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
    return data


def environments_update(
    id: str,  # A unique identifier for the environment. [required]
    name: str = None,  # The environment name. [required]
    description: Optional[str] = None,  # A description of the environment...
    parent: Optional[str] = None,  # Environments can inherit from a single parent environment which provides values for parameters when specific environment...
    access_controlled: Optional[bool] = None,  # Indicates if access control is being enforced through grants.
    _api_host: Optional[str] = None,  # API host, read from API_HOST if not provided
    _api_key: Optional[str] = None,  # API key for bearer auth, read from API_KEY if not provided
    _api_timeout: Optional[int] = None,  # timeout for operation, read from API_TIMEOUT if not provided, defaults to 5
    _log_level: Optional[str] = None,  # log level, read from API_LOG_LEVEL if not provided, defaults to info
) -> Any:
    # handler for environments_update: PUT /api/v1/environments/{id}/
    _api_host = _api_host or _e.env_string("API_HOST", default="", except_missing=True)
    _api_key = _api_key or _e.env_string("API_KEY", except_missing=True)
    _api_timeout = _api_timeout or _e.env_int("API_TIMEOUT", default=5)
    _log_level = _log_level or _e.env_string("API_LOG_LEVEL", default="info")

    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "api/v1/environments", id)

    params = {}
    body = {}
    body["name"] = name
    if description is not None:
        body["description"] = description
    if parent is not None:
        body["parent"] = parent
    if access_controlled is not None:
        body["access_controlled"] = access_controlled

    data = _r.request("PUT", url, headers=headers, params=params, body=body, timeout=_api_timeout)
    return data


def environments_retrieve(
    id: str,  # A UUID string identifying this environment ledger. [required]
    _api_host: Optional[str] = None,  # API host, read from API_HOST if not provided
    _api_key: Optional[str] = None,  # API key for bearer auth, read from API_KEY if not provided
    _api_timeout: Optional[int] = None,  # timeout for operation, read from API_TIMEOUT if not provided, defaults to 5
    _log_level: Optional[str] = None,  # log level, read from API_LOG_LEVEL if not provided, defaults to info
) -> Any:
    # handler for environments_retrieve: GET /api/v1/environments/{id}/
    _api_host = _api_host or _e.env_string("API_HOST", default="", except_missing=True)
    _api_key = _api_key or _e.env_string("API_KEY", except_missing=True)
    _api_timeout = _api_timeout or _e.env_int("API_TIMEOUT", default=5)
    _log_level = _log_level or _e.env_string("API_LOG_LEVEL", default="info")

    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "api/v1/environments", id)

    params = {}

    data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
    return data


def environments_partial_update(
    id: str,  # A unique identifier for the environment. [required]
    name: Optional[str] = None,  # The environment name.
    description: Optional[str] = None,  # A description of the environment...
    parent: Optional[str] = None,  # Environments can inherit from a single parent environment which provides values for parameters when specific environment...
    access_controlled: Optional[bool] = None,  # Indicates if access control is being enforced through grants.
    _api_host: Optional[str] = None,  # API host, read from API_HOST if not provided
    _api_key: Optional[str] = None,  # API key for bearer auth, read from API_KEY if not provided
    _api_timeout: Optional[int] = None,  # timeout for operation, read from API_TIMEOUT if not provided, defaults to 5
    _log_level: Optional[str] = None,  # log level, read from API_LOG_LEVEL if not provided, defaults to info
) -> Any:
    # handler for environments_partial_update: PATCH /api/v1/environments/{id}/
    _api_host = _api_host or _e.env_string("API_HOST", default="", except_missing=True)
    _api_key = _api_key or _e.env_string("API_KEY", except_missing=True)
    _api_timeout = _api_timeout or _e.env_int("API_TIMEOUT", default=5)
    _log_level = _log_level or _e.env_string("API_LOG_LEVEL", default="info")

    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "api/v1/environments", id)

    params = {}
    body = {}
    if name is not None:
        body["name"] = name
    if description is not None:
        body["description"] = description
    if parent is not None:
        body["parent"] = parent
    if access_controlled is not None:
        body["access_controlled"] = access_controlled

    data = _r.request("PATCH", url, headers=headers, params=params, body=body, timeout=_api_timeout)
    return data
