#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated  # noqa: F401
from typing import Optional  # noqa: F401

import typer
from rich_objects import display

from figma_cli import _arguments as _a
from figma_cli import _display as _d  # noqa: F401
from figma_cli import _exceptions as _e  # noqa: F401
from figma_cli import _logging as _l  # noqa: F401
from figma_cli import _requests as _r  # noqa: F401
from figma_cli import _tree as _t


app = typer.Typer(no_args_is_help=True, help="Manage analytics libraries style actions")


@app.command("commands", short_help="Display commands tree for actions sub-commands")
def show_commands(
    display: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show actions sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "analytics_libraries_style_actions", display, depth, search)
    return


class GroupBy(str, Enum):  # noqa: F811
    STYLE = "style"
    TEAM = "team"


@app.command("show", short_help="Get library analytics style action data.")
def get_library_analytics_style_actions(
    file_key: Annotated[str, typer.Argument(show_default=False, help="File key of the library to fetch analytics data for.")],
    cursor: Annotated[Optional[str], typer.Option(show_default=False, help="Cursor indicating what page of data to fetch. Obtained from prior API call.")] = None,
    group_by: Annotated[GroupBy, typer.Option(show_default=False, case_sensitive=False, help="A dimension to group returned analytics data by.")] = None,
    start_date: Annotated[Optional[str], typer.Option(show_default=False, help="ISO 8601 date string (YYYY-MM-DD) of the earliest week to include. Dates are rounded back to the nearest start of a week. Defaults to one year prior.")] = None,
    end_date: Annotated[Optional[str], typer.Option(show_default=False, help="ISO 8601 date string (YYYY-MM-DD) of the latest week to include. Dates are rounded forward to the nearest end of a week. Defaults to the latest computed week.")] = None,
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Returns a list of library analytics style actions data broken down by the requested dimension.
    '''
    # handler for getLibraryAnalyticsStyleActions: GET /v1/analytics/libraries/{file_key}/style/actions
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v1/analytics/libraries", file_key, "style/actions")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if group_by is None:
        missing.append("--group-by")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if cursor is not None:
        params["cursor"] = cursor
    params["group_by"] = group_by
    if start_date is not None:
        params["start_date"] = start_date
    if end_date is not None:
        params["end_date"] = end_date

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


if __name__ == "__main__":
    app()
