#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated  # noqa: F401

import typer
from rich_objects import display

from figma_cli import _arguments as _a
from figma_cli import _display as _d  # noqa: F401
from figma_cli import _exceptions as _e  # noqa: F401
from figma_cli import _logging as _l  # noqa: F401
from figma_cli import _requests as _r  # noqa: F401
from figma_cli import _tree as _t


app = typer.Typer(no_args_is_help=True, help="Manage dev-resources")


@app.command("commands", short_help="Display commands tree for dev-resources sub-commands")
def show_commands(
    display: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show dev-resources sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "dev_resources", display, depth, search)
    return


@app.command("create", short_help="Create dev resources")
def post_dev_resources(
    dev_resources_name: Annotated[str, typer.Option(show_default=False, help="The name of the dev resource.")] = None,
    dev_resources_url: Annotated[str, typer.Option(show_default=False, help="The URL of the dev resource.")] = None,
    dev_resources_file_key: Annotated[str, typer.Option(show_default=False, help="The file key where the dev resource belongs.")] = None,
    dev_resources_node_id: Annotated[str, typer.Option(show_default=False, help="The target node to attach the dev resource to.")] = None,
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Bulk create dev resources across multiple files.
    Dev resources that are successfully created will show up in the links_created array in the response.

    If there are any dev resources that cannot be created, you may still get a 200 response. These resources will show up in
    the errors array. Some reasons a dev resource cannot be created include:

    - Resource points to a `file_key` that cannot be found.
    - The node already has the maximum of 10 dev resources.
    - Another dev resource for the node has the same url.
    '''
    # handler for postDevResources: POST /v1/dev_resources
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "v1/dev_resources")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if dev_resources_name is None:
        missing.append("--dev-resources-name")
    if dev_resources_url is None:
        missing.append("--dev-resources-url")
    if dev_resources_file_key is None:
        missing.append("--dev-resources-file-key")
    if dev_resources_node_id is None:
        missing.append("--dev-resources-node-id")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    body = {}
    dev_resources = {}
    dev_resources["name"] = dev_resources_name
    dev_resources["url"] = dev_resources_url
    dev_resources["file_key"] = dev_resources_file_key
    dev_resources["node_id"] = dev_resources_node_id
    # stitch together the sub-objects
    if dev_resources:
        body["dev_resources"] = [dev_resources]  # convert to list

    try:
        data = _r.request("POST", url, headers=headers, params=params, body=body, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("set", short_help="Update dev resources")
def put_dev_resources(
    dev_resources_id: Annotated[str, typer.Option(show_default=False, help="Unique identifier of the dev resource")] = None,
    dev_resources_name: Annotated[str | None, typer.Option(show_default=False, help="The name of the dev resource.")] = None,
    dev_resources_url: Annotated[str | None, typer.Option(show_default=False, help="The URL of the dev resource.")] = None,
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Bulk update dev resources across multiple files.

    Ids for dev resources that are successfully updated will show up in the `links_updated` array in the response.

    If there are any dev resources that cannot be updated, you may still get a 200 response. These resources will show up in
    the `errors` array.
    '''
    # handler for putDevResources: PUT /v1/dev_resources
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "v1/dev_resources")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if dev_resources_id is None:
        missing.append("--dev-resources-id")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    body = {}
    dev_resources = {}
    dev_resources["id"] = dev_resources_id
    if dev_resources_name is not None:
        dev_resources["name"] = dev_resources_name
    if dev_resources_url is not None:
        dev_resources["url"] = dev_resources_url
    # stitch together the sub-objects
    if dev_resources:
        body["dev_resources"] = [dev_resources]  # convert to list

    try:
        data = _r.request("PUT", url, headers=headers, params=params, body=body, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


if __name__ == "__main__":
    app()
