#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated  # noqa: F401
from typing import Optional  # noqa: F401

import typer
from rich_objects import display

from figma_cli import _arguments as _a
from figma_cli import _display as _d  # noqa: F401
from figma_cli import _exceptions as _e  # noqa: F401
from figma_cli import _logging as _l  # noqa: F401
from figma_cli import _requests as _r  # noqa: F401
from figma_cli import _tree as _t


app = typer.Typer(no_args_is_help=True, help="Manage files nodes")


@app.command("commands", short_help="Display commands tree for nodes sub-commands")
def show_commands(
    display: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show nodes sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "files_nodes", display, depth, search)
    return


@app.command("show", short_help="Get file JSON for specific nodes")
def get_file_nodes(
    file_key: Annotated[str, typer.Argument(show_default=False, help="File to export JSON from. This can be a file key or branch key. Use `GET /v1/files/:key` with the `branch_data` query param to get the branch key.")],
    ids: Annotated[str, typer.Option(show_default=False, help="A comma separated list of node IDs to retrieve and convert.")] = None,
    version: Annotated[Optional[str], typer.Option(show_default=False, help="A specific version ID to get. Omitting this will get the current version of the file.")] = None,
    depth: Annotated[Optional[float], typer.Option(show_default=False, help="Positive integer representing how deep into the node tree to traverse. For example, setting this to 1 will return only the children directly underneath the desired nodes. Not setting this parameter returns all nodes.")] = None,
    geometry: Annotated[Optional[str], typer.Option(show_default=False, help="Set to \"paths\" to export vector data.")] = None,
    plugin_data: Annotated[Optional[str], typer.Option(show_default=False, help="A comma separated list of plugin IDs and/or the string \"shared\". Any data present in the document written by those plugins will be included in the result in the `pluginData` and `sharedPluginData` properties.")] = None,
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Returns the nodes referenced to by `ids` as a JSON object. The nodes are retrieved from the Figma file referenced to by
    `file_key`.

    The node ID and file key can be parsed from any Figma node url: `https://www.figma.com/file/{file_key}/{title}?node-
    id={id}`

    The `name`, `lastModified`, `thumbnailUrl`, `editorType`, and `version` attributes are all metadata of the specified
    file.

    The `linkAccess` field describes the file link share permission level. There are 5 types of permissions a shared link
    can have: `"inherit"`, `"view"`, `"edit"`, `"org_view"`, and `"org_edit"`. `"inherit"` is the default permission applied
    to files created in a team project, and will inherit the project's permissions. `"org_view"` and `"org_edit"` restrict
    the link to org users.

    The `document` attribute contains a Node of type `DOCUMENT`.

    The `components` key contains a mapping from node IDs to component metadata. This is to help you determine which
    components each instance comes from.

    By default, no vector data is returned. To return vector data, pass the geometry=paths parameter to the endpoint.
    Each node can also inherit properties from applicable styles. The styles key contains a mapping from style IDs to style
    metadata.

    Important: the nodes map may contain values that are `null`. This may be due to the node id not existing within the
    specified file.
    '''
    # handler for getFileNodes: GET /v1/files/{file_key}/nodes
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v1/files", file_key, "nodes")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if ids is None:
        missing.append("--ids")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    params["ids"] = ids
    if version is not None:
        params["version"] = version
    if depth is not None:
        params["depth"] = depth
    if geometry is not None:
        params["geometry"] = geometry
    if plugin_data is not None:
        params["plugin_data"] = plugin_data

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


if __name__ == "__main__":
    app()
