#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated  # noqa: F401

import typer
from rich_objects import display

from figma_cli import _arguments as _a
from figma_cli import _display as _d  # noqa: F401
from figma_cli import _exceptions as _e  # noqa: F401
from figma_cli import _logging as _l  # noqa: F401
from figma_cli import _requests as _r  # noqa: F401
from figma_cli import _tree as _t


app = typer.Typer(no_args_is_help=True, help="Manage files comments reactions")


@app.command("commands", short_help="Display commands tree for reactions sub-commands")
def show_commands(
    display: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show reactions sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "files_comments_reactions", display, depth, search)
    return


@app.command("create", short_help="Add a reaction to a comment")
def post_comment_reaction(
    file_key: Annotated[str, typer.Argument(show_default=False, help="File to post comment reactions to. This can be a file key or branch key. Use `GET /v1/files/:key` with the `branch_data` query param to get the branch key.")],
    comment_id: Annotated[str, typer.Argument(show_default=False, help="ID of comment to react to.")],
    emoji: Annotated[str, typer.Option(show_default=False, help="The emoji type of reaction as shortcode (e.g. `:heart:`, `:+1::skin-tone-2:`). The list of accepted emoji shortcodes can be found in [this file](https://raw.githubusercontent.com/missive/emoji-mart/main/packages/emoji-mart-data/sets/14/native.json) under the top-level emojis and aliases fields, with optional skin tone modifiers when applicable.")] = None,
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Posts a new comment reaction on a file comment.
    '''
    # handler for postCommentReaction: POST /v1/files/{file_key}/comments/{comment_id}/reactions
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "v1/files", file_key, "comments", comment_id, "reactions")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if emoji is None:
        missing.append("--emoji")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    body = {}
    body["emoji"] = emoji

    try:
        data = _r.request("POST", url, headers=headers, params=params, body=body, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("delete", short_help="Delete a reaction")
def delete_comment_reaction(
    file_key: Annotated[str, typer.Argument(show_default=False, help="File to delete comment reaction from. This can be a file key or branch key. Use `GET /v1/files/:key` with the `branch_data` query param to get the branch key.")],
    comment_id: Annotated[str, typer.Argument(show_default=False, help="ID of comment to delete reaction from.")],
    emoji: Annotated[str, typer.Option(show_default=False, help="The emoji type of reaction as shortcode (e.g. `:heart:`, `:+1::skin-tone-2:`). The list of accepted emoji shortcodes can be found in [this file](https://raw.githubusercontent.com/missive/emoji-mart/main/packages/emoji-mart-data/sets/14/native.json) under the top-level emojis and aliases fields, with optional skin tone modifiers when applicable.")] = None,
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Deletes a specific comment reaction. Only the person who made the reaction is allowed to delete it.
    '''
    # handler for deleteCommentReaction: DELETE /v1/files/{file_key}/comments/{comment_id}/reactions
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v1/files", file_key, "comments", comment_id, "reactions")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if emoji is None:
        missing.append("--emoji")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    params["emoji"] = emoji

    try:
        data = _r.request("DELETE", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("show", short_help="Get reactions for a comment")
def get_comment_reactions(
    file_key: Annotated[str, typer.Argument(show_default=False, help="File to get comment containing reactions from. This can be a file key or branch key. Use `GET /v1/files/:key` with the `branch_data` query param to get the branch key.")],
    comment_id: Annotated[str, typer.Argument(show_default=False, help="ID of comment to get reactions from.")],
    cursor: Annotated[str | None, typer.Option(show_default=False, help="Cursor for pagination, retrieved from the response of the previous call.")] = None,
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Gets a paginated list of reactions left on the comment.
    '''
    # handler for getCommentReactions: GET /v1/files/{file_key}/comments/{comment_id}/reactions
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v1/files", file_key, "comments", comment_id, "reactions")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if cursor is not None:
        params["cursor"] = cursor

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


if __name__ == "__main__":
    app()
