#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated  # noqa: F401
from typing import Optional  # noqa: F401

import typer
from rich_objects import display

from figma_cli import _arguments as _a
from figma_cli import _display as _d  # noqa: F401
from figma_cli import _exceptions as _e  # noqa: F401
from figma_cli import _logging as _l  # noqa: F401
from figma_cli import _requests as _r  # noqa: F401
from figma_cli import _tree as _t
from figma_cli.files_comments import app as files_comments
from figma_cli.files_dev_resources import app as files_dev_resources
from figma_cli.files_variables import app as files_variables

app = typer.Typer(no_args_is_help=True, help="Manage files")
app.add_typer(files_comments, name="comments")
app.add_typer(files_dev_resources, name="dev-resources")
app.add_typer(files_variables, name="variables")


@app.command("commands", short_help="Display commands tree for files sub-commands")
def show_commands(
    display: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show files sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "files", display, depth, search)
    return


@app.command("component-sets", short_help="Get file component sets")
def get_file_component_sets(
    file_key: Annotated[str, typer.Argument(show_default=False, help="File to list component sets from. This must be a main file key, not a branch key, as it is not possible to publish from branches.")],
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Get a list of published component sets within a file library.
    '''
    # handler for getFileComponentSets: GET /v1/files/{file_key}/component_sets
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v1/files", file_key, "component_sets")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("components", short_help="Get file components")
def get_file_components(
    file_key: Annotated[str, typer.Argument(show_default=False, help="File to list components from. This must be a main file key, not a branch key, as it is not possible to publish from branches.")],
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Get a list of published components within a file library.
    '''
    # handler for getFileComponents: GET /v1/files/{file_key}/components
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v1/files", file_key, "components")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("images", short_help="Get image fills")
def get_image_fills(
    file_key: Annotated[str, typer.Argument(show_default=False, help="File to get image URLs from. This can be a file key or branch key. Use `GET /v1/files/:key` with the `branch_data` query param to get the branch key.")],
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Returns download links for all images present in image fills in a document. Image fills are how Figma represents any
    user supplied images. When you drag an image into Figma, we create a rectangle with a single fill that represents the
    image, and the user is able to transform the rectangle (and properties on the fill) as they wish.

    This endpoint returns a mapping from image references to the URLs at which the images may be download. Image URLs will
    expire after no more than 14 days. Image references are located in the output of the GET files endpoint under the
    `imageRef` attribute in a `Paint`.
    '''
    # handler for getImageFills: GET /v1/files/{file_key}/images
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v1/files", file_key, "images")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("meta", short_help="Get file metadata")
def get_file_meta(
    file_key: Annotated[str, typer.Argument(show_default=False, help="File to get metadata for. This can be a file key or branch key. Use `GET /v1/files/:key` with the `branch_data` query param to get the branch key.")],
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Get file metadata
    '''
    # handler for getFileMeta: GET /v1/files/{file_key}/meta
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v1/files", file_key, "meta")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("nodes", short_help="Get file JSON for specific nodes")
def get_file_nodes(
    file_key: Annotated[str, typer.Argument(show_default=False, help="File to export JSON from. This can be a file key or branch key. Use `GET /v1/files/:key` with the `branch_data` query param to get the branch key.")],
    ids: Annotated[str, typer.Option(show_default=False, help="A comma separated list of node IDs to retrieve and convert.")] = None,
    version: Annotated[Optional[str], typer.Option(show_default=False, help="A specific version ID to get. Omitting this will get the current version of the file.")] = None,
    depth: Annotated[Optional[float], typer.Option(show_default=False, help="Positive integer representing how deep into the node tree to traverse. For example, setting this to 1 will return only the children directly underneath the desired nodes. Not setting this parameter returns all nodes.")] = None,
    geometry: Annotated[Optional[str], typer.Option(show_default=False, help="Set to \"paths\" to export vector data.")] = None,
    plugin_data: Annotated[Optional[str], typer.Option(show_default=False, help="A comma separated list of plugin IDs and/or the string \"shared\". Any data present in the document written by those plugins will be included in the result in the `pluginData` and `sharedPluginData` properties.")] = None,
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Returns the nodes referenced to by `ids` as a JSON object. The nodes are retrieved from the Figma file referenced to by
    `file_key`.

    The node ID and file key can be parsed from any Figma node url: `https://www.figma.com/file/{file_key}/{title}?node-
    id={id}`

    The `name`, `lastModified`, `thumbnailUrl`, `editorType`, and `version` attributes are all metadata of the specified
    file.

    The `linkAccess` field describes the file link share permission level. There are 5 types of permissions a shared link
    can have: `"inherit"`, `"view"`, `"edit"`, `"org_view"`, and `"org_edit"`. `"inherit"` is the default permission applied
    to files created in a team project, and will inherit the project's permissions. `"org_view"` and `"org_edit"` restrict
    the link to org users.

    The `document` attribute contains a Node of type `DOCUMENT`.

    The `components` key contains a mapping from node IDs to component metadata. This is to help you determine which
    components each instance comes from.

    By default, no vector data is returned. To return vector data, pass the geometry=paths parameter to the endpoint.
    Each node can also inherit properties from applicable styles. The styles key contains a mapping from style IDs to style
    metadata.

    Important: the nodes map may contain values that are `null`. This may be due to the node id not existing within the
    specified file.
    '''
    # handler for getFileNodes: GET /v1/files/{file_key}/nodes
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v1/files", file_key, "nodes")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if ids is None:
        missing.append("--ids")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    params["ids"] = ids
    if version is not None:
        params["version"] = version
    if depth is not None:
        params["depth"] = depth
    if geometry is not None:
        params["geometry"] = geometry
    if plugin_data is not None:
        params["plugin_data"] = plugin_data

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("show", short_help="Get file JSON")
def get_file(
    file_key: Annotated[str, typer.Argument(show_default=False, help="File to export JSON from. This can be a file key or branch key. Use `GET /v1/files/:key` with the `branch_data` query param to get the branch key.")],
    version: Annotated[Optional[str], typer.Option(show_default=False, help="A specific version ID to get. Omitting this will get the current version of the file.")] = None,
    ids: Annotated[Optional[str], typer.Option(show_default=False, help="Comma separated list of nodes that you care about in the document. If specified, only a subset of the document will be returned corresponding to the nodes listed, their children, and everything between the root node and the listed nodes.")] = None,
    depth: Annotated[Optional[float], typer.Option(show_default=False, help="Positive integer representing how deep into the document tree to traverse. For example, setting this to 1 returns only Pages, setting it to 2 returns Pages and all top level objects on each page. Not setting this parameter returns all nodes.")] = None,
    geometry: Annotated[Optional[str], typer.Option(show_default=False, help="Set to \"paths\" to export vector data.")] = None,
    plugin_data: Annotated[Optional[str], typer.Option(show_default=False, help="A comma separated list of plugin IDs and/or the string \"shared\". Any data present in the document written by those plugins will be included in the result in the `pluginData` and `sharedPluginData` properties.")] = None,
    branch_data: Annotated[Optional[bool], typer.Option("--branch-data/--no-branch-data", help="Returns branch metadata for the requested file. If the file is a branch, the main file\'s key will be included in the returned response. If the file has branches, their metadata will be included in the returned response. Default: false.")] = False,
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Returns the document identified by `file_key` as a JSON object. The file key can be parsed from any Figma file url:
    `https://www.figma.com/file/{file_key}/{title}`.

    The `document` property contains a node of type `DOCUMENT`.

    The `components` property contains a mapping from node IDs to component metadata. This is to help you determine which
    components each instance comes from.
    '''
    # handler for getFile: GET /v1/files/{file_key}
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v1/files", file_key)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if version is not None:
        params["version"] = version
    if ids is not None:
        params["ids"] = ids
    if depth is not None:
        params["depth"] = depth
    if geometry is not None:
        params["geometry"] = geometry
    if plugin_data is not None:
        params["plugin_data"] = plugin_data
    if branch_data is not None:
        params["branch_data"] = branch_data

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("styles", short_help="Get file styles")
def get_file_styles(
    file_key: Annotated[str, typer.Argument(show_default=False, help="File to list styles from. This must be a main file key, not a branch key, as it is not possible to publish from branches.")],
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Get a list of published styles within a file library.
    '''
    # handler for getFileStyles: GET /v1/files/{file_key}/styles
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v1/files", file_key, "styles")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("versions", short_help="Get versions of a file")
def get_file_versions(
    file_key: Annotated[str, typer.Argument(show_default=False, help="File to get version history from. This can be a file key or branch key. Use `GET /v1/files/:key` with the `branch_data` query param to get the branch key.")],
    page_size: Annotated[Optional[float], typer.Option(max=50, show_default=False, help="The number of items returned in a page of the response. If not included, `page_size` is `30`.")] = None,
    before: Annotated[Optional[float], typer.Option(show_default=False, help="A version ID for one of the versions in the history. Gets versions before this ID. Used for paginating. If the response is not paginated, this link returns the same data in the current response.")] = None,
    after: Annotated[Optional[float], typer.Option(show_default=False, help="A version ID for one of the versions in the history. Gets versions after this ID. Used for paginating. If the response is not paginated, this property is not included.")] = None,
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    This endpoint fetches the version history of a file, allowing you to see the progression of a file over time. You can
    then use this information to render a specific version of the file, via another endpoint.
    '''
    # handler for getFileVersions: GET /v1/files/{file_key}/versions
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v1/files", file_key, "versions")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if page_size is not None:
        params["page_size"] = page_size
    if before is not None:
        params["before"] = before
    if after is not None:
        params["after"] = after

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


if __name__ == "__main__":
    app()
