#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated  # noqa: F401
from typing import Optional  # noqa: F401

import typer
from rich_objects import display

from figma_cli import _arguments as _a
from figma_cli import _display as _d  # noqa: F401
from figma_cli import _exceptions as _e  # noqa: F401
from figma_cli import _logging as _l  # noqa: F401
from figma_cli import _requests as _r  # noqa: F401
from figma_cli import _tree as _t


app = typer.Typer(no_args_is_help=True, help="Manage images")


@app.command("commands", short_help="Display commands tree for images sub-commands")
def show_commands(
    display: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show images sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "images", display, depth, search)
    return


class Format(str, Enum):  # noqa: F811
    JPG = "jpg"
    PNG = "png"
    SVG = "svg"
    PDF = "pdf"


@app.command("show", short_help="Render images of file nodes")
def get_images(
    file_key: Annotated[str, typer.Argument(show_default=False, help="File to export images from. This can be a file key or branch key. Use `GET /v1/files/:key` with the `branch_data` query param to get the branch key.")],
    ids: Annotated[str, typer.Option(show_default=False, help="A comma separated list of node IDs to render.")] = None,
    version: Annotated[Optional[str], typer.Option(show_default=False, help="A specific version ID to get. Omitting this will get the current version of the file.")] = None,
    scale: Annotated[Optional[float], typer.Option(min=0.01, max=4, show_default=False, help="A number between 0.01 and 4, the image scaling factor.")] = None,
    format_: Annotated[Optional[Format], typer.Option("--format", case_sensitive=False, help="A string enum for the image output format.")] = "png",
    svg_outline_text: Annotated[Optional[bool], typer.Option("--svg-outline-text/--no-svg-outline-text", help="Whether text elements are rendered as outlines (vector paths) or as `<text>` elements in SVGs.")] = True,
    svg_include_id: Annotated[Optional[bool], typer.Option("--svg-include-id/--no-svg-include-id", help="Whether to include id attributes for all SVG elements. Adds the layer name to the `id` attribute of an svg element.")] = False,
    svg_include_node_id: Annotated[Optional[bool], typer.Option("--svg-include-node-id/--no-svg-include-node-id", help="Whether to include node id attributes for all SVG elements. Adds the node id to a `data-node-id` attribute of an svg element.")] = False,
    svg_simplify_stroke: Annotated[Optional[bool], typer.Option("--svg-simplify-stroke/--no-svg-simplify-stroke", help="Whether to simplify inside/outside strokes and use stroke attribute if possible instead of `<mask>`.")] = True,
    contents_only: Annotated[Optional[bool], typer.Option("--contents-only/--no-contents-only", help="Whether content that overlaps the node should be excluded from rendering. Passing false (i.e., rendering overlaps) may increase processing time, since more of the document must be included in rendering.")] = True,
    use_absolute_bounds: Annotated[Optional[bool], typer.Option("--use-absolute-bounds/--no-use-absolute-bounds", help="Use the full dimensions of the node regardless of whether or not it is cropped or the space around it is empty. Use this to export text nodes without cropping.")] = False,
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Renders images from a file.

    If no error occurs, `"images"` will be populated with a map from node IDs to URLs of the rendered images, and `"status"`
    will be omitted. The image assets will expire after 30 days. Images up to 32 megapixels can be exported. Any images that
    are larger will be scaled down.

    Important: the image map may contain values that are `null`. This indicates that rendering of that specific node has
    failed. This may be due to the node id not existing, or other reasons such has the node having no renderable components.
    It is guaranteed that any node that was requested for rendering will be represented in this map whether or not the
    render succeeded.

    To render multiple images from the same file, use the `ids` query parameter to specify multiple node ids.

    ```
    GET /v1/images/:key?ids=1:2,1:3,1:4
    ```
    '''
    # handler for getImages: GET /v1/images/{file_key}
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v1/images", file_key)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if ids is None:
        missing.append("--ids")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    params["ids"] = ids
    if version is not None:
        params["version"] = version
    if scale is not None:
        params["scale"] = scale
    if format_ is not None:
        params["format"] = format_
    if svg_outline_text is not None:
        params["svg_outline_text"] = svg_outline_text
    if svg_include_id is not None:
        params["svg_include_id"] = svg_include_id
    if svg_include_node_id is not None:
        params["svg_include_node_id"] = svg_include_node_id
    if svg_simplify_stroke is not None:
        params["svg_simplify_stroke"] = svg_simplify_stroke
    if contents_only is not None:
        params["contents_only"] = contents_only
    if use_absolute_bounds is not None:
        params["use_absolute_bounds"] = use_absolute_bounds

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


if __name__ == "__main__":
    app()
