#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated  # noqa: F401

import typer
from rich_objects import display

from figma_cli import _arguments as _a
from figma_cli import _display as _d  # noqa: F401
from figma_cli import _exceptions as _e  # noqa: F401
from figma_cli import _logging as _l  # noqa: F401
from figma_cli import _requests as _r  # noqa: F401
from figma_cli import _tree as _t
from figma_cli.analytics import app as analytics
from figma_cli.dev_resources import app as dev_resources
from figma_cli.files import app as files
from figma_cli.projects import app as projects
from figma_cli.teams import app as teams
from figma_cli.webhooks import app as webhooks

app = typer.Typer(no_args_is_help=True, help="This is the OpenAPI specification for the [Figma REST API](https://www.figma.com...")
app.add_typer(analytics, name="analytics")
app.add_typer(dev_resources, name="dev-resources")
app.add_typer(files, name="files")
app.add_typer(projects, name="projects")
app.add_typer(teams, name="teams")
app.add_typer(webhooks, name="webhooks")


@app.command("commands", short_help="Display commands tree for main sub-commands")
def show_commands(
    display: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show main sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "main", display, depth, search)
    return


class Order(str, Enum):  # noqa: F811
    ASC = "asc"
    DESC = "desc"


@app.command("activity-logs", short_help="Get activity logs")
def get_activity_logs(
    events: Annotated[str | None, typer.Option(show_default=False, help="Event type(s) to include in the response. Can have multiple values separated by comma. All events are returned by default.")] = None,
    start_time: Annotated[float | None, typer.Option(show_default=False, help="Unix timestamp of the least recent event to include. This param defaults to one year ago if unspecified.")] = None,
    end_time: Annotated[float | None, typer.Option(show_default=False, help="Unix timestamp of the most recent event to include. This param defaults to the current timestamp if unspecified.")] = None,
    limit: Annotated[float | None, typer.Option(show_default=False, help="Maximum number of events to return. This param defaults to 1000 if unspecified.")] = None,
    order: Annotated[Order | None, typer.Option(case_sensitive=False, help="Event order by timestamp. This param can be either \"asc\" (default) or \"desc\".")] = "asc",
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Returns a list of activity log events
    '''
    # handler for getActivityLogs: GET /v1/activity_logs
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v1/activity_logs")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if events is not None:
        params["events"] = events
    if start_time is not None:
        params["start_time"] = start_time
    if end_time is not None:
        params["end_time"] = end_time
    if limit is not None:
        params["limit"] = limit
    if order is not None:
        params["order"] = order

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("component-sets", short_help="Get component set")
def get_component_set(
    key: Annotated[str, typer.Argument(show_default=False, help="The unique identifier of the component set.")],
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Get metadata on a published component set by key.
    '''
    # handler for getComponentSet: GET /v1/component_sets/{key}
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v1/component_sets", key)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("components", short_help="Get component")
def get_component(
    key: Annotated[str, typer.Argument(show_default=False, help="The unique identifier of the component.")],
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Get metadata on a component by key.
    '''
    # handler for getComponent: GET /v1/components/{key}
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v1/components", key)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


class Format(str, Enum):  # noqa: F811
    JPG = "jpg"
    PNG = "png"
    SVG = "svg"
    PDF = "pdf"


@app.command("images", short_help="Render images of file nodes")
def get_images(
    file_key: Annotated[str, typer.Argument(show_default=False, help="File to export images from. This can be a file key or branch key. Use `GET /v1/files/:key` with the `branch_data` query param to get the branch key.")],
    ids: Annotated[str, typer.Option(show_default=False, help="A comma separated list of node IDs to render.")] = None,
    version: Annotated[str | None, typer.Option(show_default=False, help="A specific version ID to get. Omitting this will get the current version of the file.")] = None,
    scale: Annotated[float | None, typer.Option(min=0.01, max=4, show_default=False, help="A number between 0.01 and 4, the image scaling factor.")] = None,
    format_: Annotated[Format | None, typer.Option("--format", case_sensitive=False, help="A string enum for the image output format.")] = "png",
    svg_outline_text: Annotated[bool | None, typer.Option("--svg-outline-text/--no-svg-outline-text", help="Whether text elements are rendered as outlines (vector paths) or as `<text>` elements in SVGs.")] = True,
    svg_include_id: Annotated[bool | None, typer.Option("--svg-include-id/--no-svg-include-id", help="Whether to include id attributes for all SVG elements. Adds the layer name to the `id` attribute of an svg element.")] = False,
    svg_include_node_id: Annotated[bool | None, typer.Option("--svg-include-node-id/--no-svg-include-node-id", help="Whether to include node id attributes for all SVG elements. Adds the node id to a `data-node-id` attribute of an svg element.")] = False,
    svg_simplify_stroke: Annotated[bool | None, typer.Option("--svg-simplify-stroke/--no-svg-simplify-stroke", help="Whether to simplify inside/outside strokes and use stroke attribute if possible instead of `<mask>`.")] = True,
    contents_only: Annotated[bool | None, typer.Option("--contents-only/--no-contents-only", help="Whether content that overlaps the node should be excluded from rendering. Passing false (i.e., rendering overlaps) may increase processing time, since more of the document must be included in rendering.")] = True,
    use_absolute_bounds: Annotated[bool | None, typer.Option("--use-absolute-bounds/--no-use-absolute-bounds", help="Use the full dimensions of the node regardless of whether or not it is cropped or the space around it is empty. Use this to export text nodes without cropping.")] = False,
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Renders images from a file.

    If no error occurs, `"images"` will be populated with a map from node IDs to URLs of the rendered images, and `"status"`
    will be omitted. The image assets will expire after 30 days. Images up to 32 megapixels can be exported. Any images that
    are larger will be scaled down.

    Important: the image map may contain values that are `null`. This indicates that rendering of that specific node has
    failed. This may be due to the node id not existing, or other reasons such has the node having no renderable components.
    It is guaranteed that any node that was requested for rendering will be represented in this map whether or not the
    render succeeded.

    To render multiple images from the same file, use the `ids` query parameter to specify multiple node ids.

    ```
    GET /v1/images/:key?ids=1:2,1:3,1:4
    ```
    '''
    # handler for getImages: GET /v1/images/{file_key}
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v1/images", file_key)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if ids is None:
        missing.append("--ids")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    params["ids"] = ids
    if version is not None:
        params["version"] = version
    if scale is not None:
        params["scale"] = scale
    if format_ is not None:
        params["format"] = format_
    if svg_outline_text is not None:
        params["svg_outline_text"] = svg_outline_text
    if svg_include_id is not None:
        params["svg_include_id"] = svg_include_id
    if svg_include_node_id is not None:
        params["svg_include_node_id"] = svg_include_node_id
    if svg_simplify_stroke is not None:
        params["svg_simplify_stroke"] = svg_simplify_stroke
    if contents_only is not None:
        params["contents_only"] = contents_only
    if use_absolute_bounds is not None:
        params["use_absolute_bounds"] = use_absolute_bounds

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("me", short_help="Get current user")
def get_me(
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Returns the user information for the currently authenticated user.
    '''
    # handler for getMe: GET /v1/me
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v1/me")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("payments", short_help="Get payments")
def get_payments(
    plugin_payment_token: Annotated[str | None, typer.Option(show_default=False, help="Short-lived token returned from \"getPluginPaymentTokenAsync\" in the plugin payments API and used to authenticate to this endpoint. Read more about generating this token through \"Calling the Payments REST API from a plugin or widget\" below.")] = None,
    user_id: Annotated[str | None, typer.Option(show_default=False, help="The ID of the user to query payment information about. You can get the user ID by having the user OAuth2 to the Figma REST API.")] = None,
    community_file_id: Annotated[str | None, typer.Option(show_default=False, help="The ID of the Community file to query a user\'s payment information on. You can get the Community file ID from the file\'s Community page (look for the number after \"file/\" in the URL). Provide exactly one of \"community_file_id\", \"plugin_id\", or \"widget_id\".")] = None,
    plugin_id: Annotated[str | None, typer.Option(show_default=False, help="The ID of the plugin to query a user\'s payment information on. You can get the plugin ID from the plugin\'s manifest, or from the plugin\'s Community page (look for the number after \"plugin/\" in the URL). Provide exactly one of \"community_file_id\", \"plugin_id\", or \"widget_id\".")] = None,
    widget_id: Annotated[str | None, typer.Option(show_default=False, help="The ID of the widget to query a user\'s payment information on. You can get the widget ID from the widget\'s manifest, or from the widget\'s Community page (look for the number after \"widget/\" in the URL). Provide exactly one of \"community_file_id\", \"plugin_id\", or \"widget_id\".")] = None,
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    There are two methods to query for a user's payment information on a plugin, widget, or Community file. The first
    method, using plugin payment tokens, is typically used when making queries from a plugin's or widget's code. The second
    method, providing a user ID and resource ID, is typically used when making queries from anywhere else.

    Note that you can only query for resources that you own. In most cases, this means that you can only query resources
    that you originally created.
    '''
    # handler for getPayments: GET /v1/payments
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v1/payments")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if plugin_payment_token is not None:
        params["plugin_payment_token"] = plugin_payment_token
    if user_id is not None:
        params["user_id"] = user_id
    if community_file_id is not None:
        params["community_file_id"] = community_file_id
    if plugin_id is not None:
        params["plugin_id"] = plugin_id
    if widget_id is not None:
        params["widget_id"] = widget_id

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("styles", short_help="Get style")
def get_style(
    key: Annotated[str, typer.Argument(show_default=False, help="The unique identifier of the style.")],
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Get metadata on a style by key.
    '''
    # handler for getStyle: GET /v1/styles/{key}
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v1/styles", key)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


if __name__ == "__main__":
    app()
