#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated  # noqa: F401
from typing import Optional  # noqa: F401

import typer
from rich_objects import display

from figma_cli import _arguments as _a
from figma_cli import _display as _d  # noqa: F401
from figma_cli import _exceptions as _e  # noqa: F401
from figma_cli import _logging as _l  # noqa: F401
from figma_cli import _requests as _r  # noqa: F401
from figma_cli import _tree as _t


app = typer.Typer(no_args_is_help=True, help="Manage payments")


@app.command("commands", short_help="Display commands tree for payments sub-commands")
def show_commands(
    display: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show payments sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "payments", display, depth, search)
    return


@app.command("show", short_help="Get payments")
def get_payments(
    plugin_payment_token: Annotated[Optional[str], typer.Option(show_default=False, help="Short-lived token returned from \"getPluginPaymentTokenAsync\" in the plugin payments API and used to authenticate to this endpoint. Read more about generating this token through \"Calling the Payments REST API from a plugin or widget\" below.")] = None,
    user_id: Annotated[Optional[str], typer.Option(show_default=False, help="The ID of the user to query payment information about. You can get the user ID by having the user OAuth2 to the Figma REST API.")] = None,
    community_file_id: Annotated[Optional[str], typer.Option(show_default=False, help="The ID of the Community file to query a user\'s payment information on. You can get the Community file ID from the file\'s Community page (look for the number after \"file/\" in the URL). Provide exactly one of \"community_file_id\", \"plugin_id\", or \"widget_id\".")] = None,
    plugin_id: Annotated[Optional[str], typer.Option(show_default=False, help="The ID of the plugin to query a user\'s payment information on. You can get the plugin ID from the plugin\'s manifest, or from the plugin\'s Community page (look for the number after \"plugin/\" in the URL). Provide exactly one of \"community_file_id\", \"plugin_id\", or \"widget_id\".")] = None,
    widget_id: Annotated[Optional[str], typer.Option(show_default=False, help="The ID of the widget to query a user\'s payment information on. You can get the widget ID from the widget\'s manifest, or from the widget\'s Community page (look for the number after \"widget/\" in the URL). Provide exactly one of \"community_file_id\", \"plugin_id\", or \"widget_id\".")] = None,
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    There are two methods to query for a user's payment information on a plugin, widget, or Community file. The first
    method, using plugin payment tokens, is typically used when making queries from a plugin's or widget's code. The second
    method, providing a user ID and resource ID, is typically used when making queries from anywhere else.

    Note that you can only query for resources that you own. In most cases, this means that you can only query resources
    that you originally created.
    '''
    # handler for getPayments: GET /v1/payments
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v1/payments")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if plugin_payment_token is not None:
        params["plugin_payment_token"] = plugin_payment_token
    if user_id is not None:
        params["user_id"] = user_id
    if community_file_id is not None:
        params["community_file_id"] = community_file_id
    if plugin_id is not None:
        params["plugin_id"] = plugin_id
    if widget_id is not None:
        params["widget_id"] = widget_id

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


if __name__ == "__main__":
    app()
