#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated  # noqa: F401
from typing import Optional  # noqa: F401

import typer
from rich_objects import display

from figma_cli import _arguments as _a
from figma_cli import _display as _d  # noqa: F401
from figma_cli import _exceptions as _e  # noqa: F401
from figma_cli import _logging as _l  # noqa: F401
from figma_cli import _requests as _r  # noqa: F401
from figma_cli import _tree as _t


app = typer.Typer(no_args_is_help=True, help="Manage webhooks requests")


@app.command("commands", short_help="Display commands tree for requests sub-commands")
def show_commands(
    display: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show requests sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "webhooks_requests", display, depth, search)
    return


@app.command("show", short_help="Get webhook requests")
def get_webhook_requests(
    webhook_id: Annotated[str, typer.Argument(show_default=False, help="The id of the webhook subscription you want to see events from")],
    _api_host: _a.ApiHostOption = "https://api.figma.com",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Returns all webhook requests sent within the last week. Useful for debugging.
    '''
    # handler for getWebhookRequests: GET /v2/webhooks/{webhook_id}/requests
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "v2/webhooks", webhook_id, "requests")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


if __name__ == "__main__":
    app()
