# Copyright 2025
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from typing import Any
from typing import Optional  # noqa: F401

from cloudtruth_api.opaque import _environment as _e  # noqa: F401
from cloudtruth_api.opaque import _logging as _l  # noqa: F401
from cloudtruth_api.opaque import _requests as _r  # noqa: F401


def environments_copy_create(
    id: str,  # A unique identifier for the environment. [required]
    body: Any = None,  # required fields: name
    _api_host: Optional[str] = None,  # API host, read from API_HOST if not provided
    _api_key: Optional[str] = None,  # API key for bearer auth, read from API_KEY if not provided
    _api_timeout: Optional[int] = None,  # timeout for operation, read from API_TIMEOUT if not provided, defaults to 5
    _log_level: Optional[str] = None,  # log level, read from API_LOG_LEVEL if not provided, defaults to info
) -> Any:
    # handler for environments_copy_create: POST /api/v1/environments/{id}/copy/
    _api_host = _api_host or _e.env_string("API_HOST", default="", except_missing=True)
    _api_key = _api_key or _e.env_string("API_KEY", except_missing=True)
    _api_timeout = _api_timeout or _e.env_int("API_TIMEOUT", default=5)
    _log_level = _log_level or _e.env_string("API_LOG_LEVEL", default="info")

    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "api/v1/environments", id, "copy/")

    params = {}

    data = _r.request("POST", url, headers=headers, params=params, body=body, timeout=_api_timeout)
    return data
