#!/usr/bin/env python3
# Copyright 2025
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated  # noqa: F401
from typing import Optional  # noqa: F401

import typer

from trains import _arguments as _a
from trains import _display as _d  # noqa: F401
from trains import _exceptions as _e  # noqa: F401
from trains import _logging as _l  # noqa: F401
from trains import _requests as _r  # noqa: F401
from trains import _tree as _t


app = typer.Typer(no_args_is_help=True, help="Manage bookings")


@app.command("commands", short_help="Display commands tree for bookings sub-commands")
def show_commands(
    display: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show bookings sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "bookings", display, depth, search)
    return


@app.command("create", short_help="Create a booking")
def create_booking(
    trip_id: Annotated[Optional[str], typer.Option(show_default=False, help="Identifier of the booked trip")] = None,
    passenger_name: Annotated[Optional[str], typer.Option(show_default=False, help="Name of the passenger")] = None,
    has_bicycle: Annotated[Optional[bool], typer.Option("--has-bicycle/--no-has-bicycle", show_default=False, help="Indicates whether the passenger has a bicycle.")] = None,
    has_dog: Annotated[Optional[bool], typer.Option("--has-dog/--no-has-dog", show_default=False, help="Indicates whether the passenger has a dog.")] = None,
    _api_host: _a.ApiHostOption = "https://try.microcks.io/rest/Train+Travel+API/1.0.0",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    A booking is a temporary hold on a trip. It is not confirmed until the payment is processed.
    '''
    # handler for create-booking: POST /bookings
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "bookings")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    body = {}
    if trip_id is not None:
        body["trip_id"] = trip_id
    if passenger_name is not None:
        body["passenger_name"] = passenger_name
    if has_bicycle is not None:
        body["has_bicycle"] = has_bicycle
    if has_dog is not None:
        body["has_dog"] = has_dog

    try:
        data = _r.request("POST", url, headers=headers, params=params, body=body, timeout=_api_timeout)
        _d.display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("delete", short_help="Delete a booking")
def delete_booking(
    booking_id: Annotated[str, typer.Argument(show_default=False, help="The ID of the booking to retrieve.")],
    _api_host: _a.ApiHostOption = "https://try.microcks.io/rest/Train+Travel+API/1.0.0",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Deletes a booking, cancelling the hold on the trip.
    '''
    # handler for delete-booking: DELETE /bookings/{bookingId}
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "bookings", booking_id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("DELETE", url, headers=headers, params=params, timeout=_api_timeout)
        _d.display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("list", short_help="List existing bookings")
def get_bookings(
    page: Annotated[Optional[int], typer.Option(min=1, help="The page number to return")] = 1,
    limit: Annotated[Optional[int], typer.Option(min=1, max=100, help="The number of items to return per page")] = 10,
    _api_host: _a.ApiHostOption = "https://try.microcks.io/rest/Train+Travel+API/1.0.0",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
    _max_count: _a.MaxCountOption = None,
) -> None:
    '''
    Returns a list of all trip bookings by the authenticated user.
    '''
    # handler for get-bookings: GET /bookings
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "bookings")
    page_info = _r.PageParams(
        max_count=_max_count,
        page_size_name="limit",
        page_size_value=limit,
        page_start_name="page",
        page_start_value=page,
        items_property_name="data",
    )
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if page is not None:
        params["page"] = page
    if limit is not None:
        params["limit"] = limit

    try:
        data = _r.depaginate(page_info, url, headers=headers, params=params, timeout=_api_timeout)
        _d.display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


class Currency(str, Enum):  # noqa: F811
    BAM = "bam"
    BGN = "bgn"
    CHF = "chf"
    EUR = "eur"
    GBP = "gbp"
    NOK = "nok"
    SEK = "sek"
    TRY_ = "try"


@app.command("payment", short_help="Pay for a Booking")
def create_booking_payment(
    booking_id: Annotated[str, typer.Argument(show_default=False, help="The ID of the booking to pay for.")],
    amount: Annotated[Optional[float], typer.Option(show_default=False, help="Amount intended to be collected by this payment. A positive decimal figure describing the amount to be collected.")] = None,
    currency: Annotated[Optional[Currency], typer.Option(show_default=False, case_sensitive=False, help="Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase.")] = None,
    source_object: Annotated[Optional[str], typer.Option(show_default=False)] = None,
    source_name: Annotated[Optional[str], typer.Option(show_default=False, help="Cardholder\'s full name as it appears on the card.")] = None,
    source_number: Annotated[Optional[str], typer.Option(show_default=False, help="The card number, as a string without any separators. On read all but the last four digits will be masked for security.")] = None,
    source_cvc: Annotated[Optional[str], typer.Option(show_default=False, help="Card security code, 3 or 4 digits usually found on the back of the card.")] = None,
    source_exp_month: Annotated[Optional[int], typer.Option(show_default=False, help="Two-digit number representing the card\'s expiration month.")] = None,
    source_exp_year: Annotated[Optional[int], typer.Option(show_default=False, help="Four-digit number representing the card\'s expiration year.")] = None,
    source_address_line1: Annotated[Optional[str], typer.Option(show_default=False)] = None,
    source_address_line2: Annotated[Optional[str], typer.Option(show_default=False)] = None,
    source_address_city: Annotated[Optional[str], typer.Option(show_default=False)] = None,
    source_address_country: Annotated[Optional[str], typer.Option(show_default=False)] = None,
    source_address_post_code: Annotated[Optional[str], typer.Option(show_default=False)] = None,
    _api_host: _a.ApiHostOption = "https://try.microcks.io/rest/Train+Travel+API/1.0.0",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    A payment is an attempt to pay for the booking, which will confirm the booking for the user and enable them to get their
    tickets.
    '''
    # handler for create-booking-payment: POST /bookings/{bookingId}/payment
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "bookings", booking_id, "payment")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    body = {}
    source = {}
    if amount is not None:
        body["amount"] = amount
    if currency is not None:
        body["currency"] = currency
    if source_object is not None:
        source["object"] = source_object
    if source_name is not None:
        source["name"] = source_name
    if source_number is not None:
        source["number"] = source_number
    if source_cvc is not None:
        source["cvc"] = source_cvc
    if source_exp_month is not None:
        source["exp_month"] = source_exp_month
    if source_exp_year is not None:
        source["exp_year"] = source_exp_year
    if source_address_line1 is not None:
        source["address_line1"] = source_address_line1
    if source_address_line2 is not None:
        source["address_line2"] = source_address_line2
    if source_address_city is not None:
        source["address_city"] = source_address_city
    if source_address_country is not None:
        source["address_country"] = source_address_country
    if source_address_post_code is not None:
        source["address_post_code"] = source_address_post_code
    # stitch together the sub-objects
    if source:
        body["source"] = source

    try:
        data = _r.request("POST", url, headers=headers, params=params, body=body, timeout=_api_timeout)
        _d.display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("show", short_help="Get a booking")
def get_booking(
    booking_id: Annotated[str, typer.Argument(show_default=False, help="The ID of the booking to retrieve.")],
    _api_host: _a.ApiHostOption = "https://try.microcks.io/rest/Train+Travel+API/1.0.0",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Returns the details of a specific booking.
    '''
    # handler for get-booking: GET /bookings/{bookingId}
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "bookings", booking_id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        _d.display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


if __name__ == "__main__":
    app()
