#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated

import typer
from rich_objects import display

from close_cli import _arguments as _a
from close_cli import _display as _d  # noqa: F401
from close_cli import _exceptions as _e
from close_cli import _logging as _l
from close_cli import _requests as _r
from close_cli import _tree as _t

app = typer.Typer(no_args_is_help=True, help="Manage activity sms")


@app.command("commands", short_help="Display commands tree for sms sub-commands")
def show_commands(
    display_opt: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show sms sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "activity_sms", display_opt, depth, search)


class AttachmentsContentType(str, Enum):  # noqa: F811
    APPLICATION_PDF = "application/pdf"
    APPLICATION_VCARD = "application/vcard"
    AUDIO_3GPP = "audio/3gpp"
    AUDIO_3GPP2 = "audio/3gpp2"
    AUDIO_L24 = "audio/L24"
    AUDIO_AC3 = "audio/ac3"
    AUDIO_AMR = "audio/amr"
    AUDIO_AMR_NB = "audio/amr-nb"
    AUDIO_BASIC = "audio/basic"
    AUDIO_MP4 = "audio/mp4"
    AUDIO_MPEG = "audio/mpeg"
    AUDIO_OGG = "audio/ogg"
    AUDIO_VND_RN_REALAUDIO = "audio/vnd.rn-realaudio"
    AUDIO_VND_WAVE = "audio/vnd.wave"
    AUDIO_WEBM = "audio/webm"
    IMAGE_BMP = "image/bmp"
    IMAGE_GIF = "image/gif"
    IMAGE_JPEG = "image/jpeg"
    IMAGE_JPG = "image/jpg"
    IMAGE_PNG = "image/png"
    IMAGE_TIFF = "image/tiff"
    TEXT_CALENDAR = "text/calendar"
    TEXT_CSV = "text/csv"
    TEXT_DIRECTORY = "text/directory"
    TEXT_RICHTEXT = "text/richtext"
    TEXT_RTF = "text/rtf"
    TEXT_VCARD = "text/vcard"
    TEXT_X_VCARD = "text/x-vcard"
    VIDEO_3GPP = "video/3gpp"
    VIDEO_3GPP_TT = "video/3gpp-tt"
    VIDEO_3GPP2 = "video/3gpp2"
    VIDEO_H261 = "video/H261"
    VIDEO_H263 = "video/H263"
    VIDEO_H263_1998 = "video/H263-1998"
    VIDEO_H263_2000 = "video/H263-2000"
    VIDEO_H264 = "video/H264"
    VIDEO_MP4 = "video/mp4"
    VIDEO_MPEG = "video/mpeg"
    VIDEO_QUICKTIME = "video/quicktime"
    VIDEO_WEBM = "video/webm"


class CallerIdMode(str, Enum):  # noqa: F811
    FIXED = "fixed"
    AUTO = "auto"
    NONE = "None"


class Direction(str, Enum):  # noqa: F811
    INBOUND = "inbound"
    OUTBOUND = "outbound"
    NONE = "None"


class Source(str, Enum):  # noqa: F811
    CLOSE_IO = "Close.io"
    EXTERNAL = "External"
    NONE = "None"


class Status(str, Enum):  # noqa: F811
    INBOX = "inbox"
    DRAFT = "draft"
    SCHEDULED = "scheduled"
    OUTBOX = "outbox"
    SENT = "sent"
    ERROR = "error"


@app.command("create", short_help="Create an SMS activity")
def activities_sms_create(
    send_to_inbox: Annotated[bool | None, typer.Option("--send-to-inbox/--no-send-to-inbox", show_default=False)] = None,
    activity_at: Annotated[datetime | None, typer.Option(show_default=False)] = None,
    attachments_content_type: Annotated[AttachmentsContentType | None, typer.Option(show_default=False, case_sensitive=False)] = None,
    attachments_filename: Annotated[str | None, typer.Option(show_default=False)] = None,
    attachments_url: Annotated[str | None, typer.Option(show_default=False)] = None,
    caller_id_mode: Annotated[CallerIdMode | None, typer.Option(show_default=False, case_sensitive=False)] = None,
    contact_id: Annotated[str | None, typer.Option(show_default=False)] = None,
    created_by: Annotated[str | None, typer.Option(show_default=False)] = None,
    date_created: Annotated[datetime | None, typer.Option(show_default=False)] = None,
    direction: Annotated[Direction | None, typer.Option(show_default=False, case_sensitive=False)] = None,
    lead_id: Annotated[str | None, typer.Option(show_default=False)] = None,
    local_phone: Annotated[str | None, typer.Option(show_default=False, help="Phone number in E.164 format")] = None,
    organization_id: Annotated[str | None, typer.Option(show_default=False)] = None,
    remote_phone: Annotated[str | None, typer.Option(show_default=False, help="Phone number in E.164 format")] = None,
    source: Annotated[Source | None, typer.Option(show_default=False, case_sensitive=False)] = None,
    status: Annotated[Status | None, typer.Option(show_default=False, case_sensitive=False)] = None,
    template_id: Annotated[str | None, typer.Option(show_default=False)] = None,
    text: Annotated[str | None, typer.Option(show_default=False)] = None,
    user_id: Annotated[str | None, typer.Option(show_default=False)] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    *status* must be one of the following:

     - `inbox` to log an already received SMS.
     - `draft` to create a draft SMS.
     - `scheduled` to send an SMS at a scheduled date and time, which must be specified in the `date_scheduled` field.
     - `outbox` to actually **send** an SMS. To delay SMS sending by a few seconds (to allow undo), specify `send_in` in
    seconds (must be less than 60).
     - `sent` to log an already sent SMS.

    Only drafts can be modified, and their status can be changed to `scheduled` (to send later) or `outbox` (to send
    immediately). Scheduled SMS, or SMS in outbox that weren't sent yet can be canceled by setting the status back to
    `draft`.

    You have to provide a `local_phone` that will be used to send the SMS. The number you choose has to be associated with a
    Phone Number of type `internal`. See the [Phone Numbers](https://developer.close.com/api/resources/phone-numbers)
    paragraph for more details.

    A `template_id` referencing an SMS Template may be provided instead of `text` to automatically render that template and
    use the content as `text`.

    When `direction` is not provided, but `status="inbox"`, `direction` will default to "inbound". Otherwise, `direction`
    defaults to "outbound".

    When creating a new SMS with the status set to `inbox`, you can pass the query parameter `send_to_inbox` with the value
    of `true`  to create a corresponding Inbox Notification for the SMS.
    '''
    # handler for activities.sms_create: POST /activity/sms/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "activity/sms/")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if status is None:
        missing.append("--status")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if send_to_inbox is not None:
        params["send_to_inbox"] = send_to_inbox
    body = {}
    attachments = {}
    if activity_at is not None:
        body["activity_at"] = activity_at
    if attachments_content_type is not None:
        attachments["content_type"] = attachments_content_type
    if attachments_filename is not None:
        attachments["filename"] = attachments_filename
    if attachments_url is not None:
        attachments["url"] = attachments_url
    if caller_id_mode is not None:
        body["caller_id_mode"] = caller_id_mode
    if contact_id is not None:
        body["contact_id"] = contact_id
    if created_by is not None:
        body["created_by"] = created_by
    if date_created is not None:
        body["date_created"] = date_created
    if direction is not None:
        body["direction"] = direction
    if lead_id is not None:
        body["lead_id"] = lead_id
    if local_phone is not None:
        body["local_phone"] = local_phone
    if organization_id is not None:
        body["organization_id"] = organization_id
    if remote_phone is not None:
        body["remote_phone"] = remote_phone
    if source is not None:
        body["source"] = source
    body["status"] = status
    if template_id is not None:
        body["template_id"] = template_id
    if text is not None:
        body["text"] = text
    if user_id is not None:
        body["user_id"] = user_id
    # stitch together the sub-objects
    if attachments:
        body["attachments"] = [attachments]  # convert to list

    try:
        data = _r.request("POST", url, headers=headers, params=params, body=body, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:  # noqa: BLE001
        _e.handle_exceptions(ex)


@app.command("delete", short_help="Delete an SMS activity")
def activities_sms_delete(
    id: Annotated[str, typer.Argument(show_default=False)],
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Delete an SMS activity
    '''
    # handler for activities.sms_delete: DELETE /activity/sms/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "activity/sms", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("DELETE", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:  # noqa: BLE001
        _e.handle_exceptions(ex)


@app.command("list", short_help="List or filter all SMS activities")
def activities_sms_list(
    _limit: Annotated[int | None, typer.Option(help="Number of results to return.")] = 100,
    _skip: Annotated[int | None, typer.Option(help="Number of results to skip before returning, for pagination.")] = 0,
    id_in: Annotated[list[str] | None, typer.Option(show_default=False, help="Filter by activity IDs (comma-separated)")] = None,
    lead_id: Annotated[list[str] | None, typer.Option(show_default=False, help="Filter by lead IDs (comma-separated)")] = None,
    contact_id: Annotated[list[str] | None, typer.Option(show_default=False, help="Filter by contact IDs (comma-separated)")] = None,
    user_id: Annotated[list[str] | None, typer.Option(show_default=False, help="Filter by user IDs (comma-separated)")] = None,
    organization_id: Annotated[str | None, typer.Option(show_default=False)] = None,
    _type: Annotated[list[str] | None, typer.Option(show_default=False, help="Filter by activity type, e.g. Call (comma-separated)")] = None,
    date_created_gte: Annotated[datetime | None, typer.Option(show_default=False)] = None,
    date_created_lte: Annotated[datetime | None, typer.Option(show_default=False)] = None,
    date_created_gt: Annotated[datetime | None, typer.Option(show_default=False)] = None,
    date_created_lt: Annotated[datetime | None, typer.Option(show_default=False)] = None,
    activity_at_gte: Annotated[datetime | None, typer.Option(show_default=False)] = None,
    activity_at_lte: Annotated[datetime | None, typer.Option(show_default=False)] = None,
    activity_at_gt: Annotated[datetime | None, typer.Option(show_default=False)] = None,
    activity_at_lt: Annotated[datetime | None, typer.Option(show_default=False)] = None,
    _fields: Annotated[str | None, typer.Option(show_default=False, help="Comma-separated list of fields to include in the response.")] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
    _max_count: _a.MaxCountOption = None,
) -> None:
    '''
    Get a list of matching SMS activities.

    MMS messages are considered SMS messages with attachments. Attachments have identical fields to email attachments
    (`url`, `filename`, `size` and `content_type`), a `media_id` uniquely identifying an attachment, and if Close was able
    to generate a thumbnail, a `thumbnail_url` too.

    Accessing `url` or `thumbnail_url` requires an authenticated session and leads to a temporarily signed S3 URL.
    '''
    # handler for activities.sms_list: GET /activity/sms/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "activity/sms/")
    page_info = _r.PageParams(
        max_count=_max_count,
        page_size_name="_limit",
        page_size_value=_limit,
        item_start_name="_skip",
        item_start_value=_skip,
    )
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if _limit is not None:
        params["_limit"] = _limit
    if _skip is not None:
        params["_skip"] = _skip
    if id_in is not None:
        params["id__in"] = id_in
    if lead_id is not None:
        params["lead_id"] = lead_id
    if contact_id is not None:
        params["contact_id"] = contact_id
    if user_id is not None:
        params["user_id"] = user_id
    if organization_id is not None:
        params["organization_id"] = organization_id
    if _type is not None:
        params["_type"] = _type
    if date_created_gte is not None:
        params["date_created__gte"] = date_created_gte
    if date_created_lte is not None:
        params["date_created__lte"] = date_created_lte
    if date_created_gt is not None:
        params["date_created__gt"] = date_created_gt
    if date_created_lt is not None:
        params["date_created__lt"] = date_created_lt
    if activity_at_gte is not None:
        params["activity_at__gte"] = activity_at_gte
    if activity_at_lte is not None:
        params["activity_at__lte"] = activity_at_lte
    if activity_at_gt is not None:
        params["activity_at__gt"] = activity_at_gt
    if activity_at_lt is not None:
        params["activity_at__lt"] = activity_at_lt
    if _fields is not None:
        params["_fields"] = _fields

    try:
        data = _r.depaginate(page_info, url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:  # noqa: BLE001
        _e.handle_exceptions(ex)


class AttachmentsContentType(str, Enum):  # noqa: F811
    APPLICATION_PDF = "application/pdf"
    APPLICATION_VCARD = "application/vcard"
    AUDIO_3GPP = "audio/3gpp"
    AUDIO_3GPP2 = "audio/3gpp2"
    AUDIO_L24 = "audio/L24"
    AUDIO_AC3 = "audio/ac3"
    AUDIO_AMR = "audio/amr"
    AUDIO_AMR_NB = "audio/amr-nb"
    AUDIO_BASIC = "audio/basic"
    AUDIO_MP4 = "audio/mp4"
    AUDIO_MPEG = "audio/mpeg"
    AUDIO_OGG = "audio/ogg"
    AUDIO_VND_RN_REALAUDIO = "audio/vnd.rn-realaudio"
    AUDIO_VND_WAVE = "audio/vnd.wave"
    AUDIO_WEBM = "audio/webm"
    IMAGE_BMP = "image/bmp"
    IMAGE_GIF = "image/gif"
    IMAGE_JPEG = "image/jpeg"
    IMAGE_JPG = "image/jpg"
    IMAGE_PNG = "image/png"
    IMAGE_TIFF = "image/tiff"
    TEXT_CALENDAR = "text/calendar"
    TEXT_CSV = "text/csv"
    TEXT_DIRECTORY = "text/directory"
    TEXT_RICHTEXT = "text/richtext"
    TEXT_RTF = "text/rtf"
    TEXT_VCARD = "text/vcard"
    TEXT_X_VCARD = "text/x-vcard"
    VIDEO_3GPP = "video/3gpp"
    VIDEO_3GPP_TT = "video/3gpp-tt"
    VIDEO_3GPP2 = "video/3gpp2"
    VIDEO_H261 = "video/H261"
    VIDEO_H263 = "video/H263"
    VIDEO_H263_1998 = "video/H263-1998"
    VIDEO_H263_2000 = "video/H263-2000"
    VIDEO_H264 = "video/H264"
    VIDEO_MP4 = "video/mp4"
    VIDEO_MPEG = "video/mpeg"
    VIDEO_QUICKTIME = "video/quicktime"
    VIDEO_WEBM = "video/webm"


class CallerIdMode(str, Enum):  # noqa: F811
    FIXED = "fixed"
    AUTO = "auto"
    NONE = "None"


class Status(str, Enum):  # noqa: F811
    INBOX = "inbox"
    DRAFT = "draft"
    SCHEDULED = "scheduled"
    OUTBOX = "outbox"
    SENT = "sent"
    ERROR = "error"


@app.command("set", short_help="Update an SMS activity")
def activities_sms_update(
    id: Annotated[str, typer.Argument(show_default=False)],
    activity_at: Annotated[datetime | None, typer.Option(show_default=False)] = None,
    attachments_content_type: Annotated[AttachmentsContentType | None, typer.Option(show_default=False, case_sensitive=False)] = None,
    attachments_filename: Annotated[str | None, typer.Option(show_default=False)] = None,
    attachments_url: Annotated[str | None, typer.Option(show_default=False)] = None,
    caller_id_mode: Annotated[CallerIdMode | None, typer.Option(show_default=False, case_sensitive=False)] = None,
    contact_id: Annotated[str | None, typer.Option(show_default=False)] = None,
    lead_id: Annotated[str | None, typer.Option(show_default=False)] = None,
    local_phone: Annotated[str | None, typer.Option(show_default=False, help="Phone number in E.164 format")] = None,
    remote_phone: Annotated[str | None, typer.Option(show_default=False, help="Phone number in E.164 format")] = None,
    status: Annotated[Status | None, typer.Option(show_default=False, case_sensitive=False)] = None,
    template_id: Annotated[str | None, typer.Option(show_default=False)] = None,
    text: Annotated[str | None, typer.Option(show_default=False)] = None,
    user_id: Annotated[str | None, typer.Option(show_default=False)] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    This can be used to modify a draft or send it once the draft is complete.

    To send an SMS immediately, you can update its `status` to `outbox`. To send it at a later time, change the `status` to
    `scheduled` and provide the desired date & time in the `date_scheduled` field.
    '''
    # handler for activities.sms_update: PUT /activity/sms/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "activity/sms", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    body = {}
    attachments = {}
    if activity_at is not None:
        body["activity_at"] = activity_at
    if attachments_content_type is not None:
        attachments["content_type"] = attachments_content_type
    if attachments_filename is not None:
        attachments["filename"] = attachments_filename
    if attachments_url is not None:
        attachments["url"] = attachments_url
    if caller_id_mode is not None:
        body["caller_id_mode"] = caller_id_mode
    if contact_id is not None:
        body["contact_id"] = contact_id
    if lead_id is not None:
        body["lead_id"] = lead_id
    if local_phone is not None:
        body["local_phone"] = local_phone
    if remote_phone is not None:
        body["remote_phone"] = remote_phone
    if status is not None:
        body["status"] = status
    if template_id is not None:
        body["template_id"] = template_id
    if text is not None:
        body["text"] = text
    if user_id is not None:
        body["user_id"] = user_id
    # stitch together the sub-objects
    if attachments:
        body["attachments"] = [attachments]  # convert to list

    try:
        data = _r.request("PUT", url, headers=headers, params=params, body=body, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:  # noqa: BLE001
        _e.handle_exceptions(ex)


@app.command("show", short_help="Get a single SMS activity")
def activities_sms_get(
    id: Annotated[str, typer.Argument(show_default=False)],
    _fields: Annotated[str | None, typer.Option(show_default=False, help="Comma-separated list of fields to include in the response.")] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Get a single SMS activity
    '''
    # handler for activities.sms_get: GET /activity/sms/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "activity/sms", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if _fields is not None:
        params["_fields"] = _fields

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:  # noqa: BLE001
        _e.handle_exceptions(ex)


if __name__ == "__main__":
    app()
