#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated  # noqa: F401

import typer
from rich_objects import display  # noqa: F401

from close_cli import _arguments as _a
from close_cli import _display as _d  # noqa: F401
from close_cli import _exceptions as _e  # noqa: F401
from close_cli import _logging as _l  # noqa: F401
from close_cli import _requests as _r  # noqa: F401
from close_cli import _tree as _t
from close_cli.activity_call import app as activity_call
from close_cli.activity_created import app as activity_created
from close_cli.activity_custom import app as activity_custom
from close_cli.activity_email import app as activity_email
from close_cli.activity_emailthread import app as activity_emailthread
from close_cli.activity_form_submission import app as activity_form_submission
from close_cli.activity_import_update import app as activity_import_update
from close_cli.activity_lead_merge import app as activity_lead_merge
from close_cli.activity_meeting import app as activity_meeting
from close_cli.activity_note import app as activity_note
from close_cli.activity_sms import app as activity_sms
from close_cli.activity_status_change import app as activity_status_change
from close_cli.activity_task_completed import app as activity_task_completed
from close_cli.activity_whatsapp_message import app as activity_whatsapp_message

app = typer.Typer(no_args_is_help=True, help="Manage activity")
app.add_typer(activity_call, name="call")
app.add_typer(activity_created, name="created")
app.add_typer(activity_custom, name="custom")
app.add_typer(activity_email, name="email")
app.add_typer(activity_emailthread, name="emailthread")
app.add_typer(activity_form_submission, name="form-submission")
app.add_typer(activity_import_update, name="import-update")
app.add_typer(activity_lead_merge, name="lead-merge")
app.add_typer(activity_meeting, name="meeting")
app.add_typer(activity_note, name="note")
app.add_typer(activity_sms, name="sms")
app.add_typer(activity_status_change, name="status-change")
app.add_typer(activity_task_completed, name="task-completed")
app.add_typer(activity_whatsapp_message, name="whatsapp-message")


@app.command("commands", short_help="Display commands tree for activity sub-commands")
def show_commands(
    display_opt: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show activity sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "activity", display_opt, depth, search)


@app.command("list", short_help="List or filter all activity types")
def activities_list(
    _limit: Annotated[int | None, typer.Option(help="Number of results to return.")] = 100,
    _skip: Annotated[int | None, typer.Option(help="Number of results to skip before returning, for pagination.")] = 0,
    id_in: Annotated[list[str] | None, typer.Option(show_default=False, help="Filter by activity IDs (comma-separated)")] = None,
    lead_id: Annotated[list[str] | None, typer.Option(show_default=False, help="Filter by lead IDs (comma-separated)")] = None,
    contact_id: Annotated[list[str] | None, typer.Option(show_default=False, help="Filter by contact IDs (comma-separated)")] = None,
    user_id: Annotated[list[str] | None, typer.Option(show_default=False, help="Filter by user IDs (comma-separated)")] = None,
    organization_id: Annotated[str | None, typer.Option(show_default=False)] = None,
    _type: Annotated[list[str] | None, typer.Option(show_default=False, help="Filter by activity type, e.g. Call (comma-separated)")] = None,
    date_created_gte: Annotated[datetime | None, typer.Option(show_default=False)] = None,
    date_created_lte: Annotated[datetime | None, typer.Option(show_default=False)] = None,
    date_created_gt: Annotated[datetime | None, typer.Option(show_default=False)] = None,
    date_created_lt: Annotated[datetime | None, typer.Option(show_default=False)] = None,
    activity_at_gte: Annotated[datetime | None, typer.Option(show_default=False)] = None,
    activity_at_lte: Annotated[datetime | None, typer.Option(show_default=False)] = None,
    activity_at_gt: Annotated[datetime | None, typer.Option(show_default=False)] = None,
    activity_at_lt: Annotated[datetime | None, typer.Option(show_default=False)] = None,
    lead_id_in: Annotated[str | None, typer.Option(show_default=False)] = None,
    user_id_in: Annotated[str | None, typer.Option(show_default=False)] = None,
    contact_id_in: Annotated[str | None, typer.Option(show_default=False)] = None,
    _type_in: Annotated[str | None, typer.Option(show_default=False)] = None,
    _fields: Annotated[str | None, typer.Option(show_default=False, help="Comma-separated list of fields to include in the response.")] = None,
    _order_by: Annotated[str | None, typer.Option(show_default=False)] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
    _max_count: _a.MaxCountOption = None,
) -> None:
    '''
    To list only a specific activity type (e.g., only `Call` or `LeadStatusChange`), use the other resources listed
    separately. When querying activities for a single lead (using the `lead_id` parameter), you can ask for multiple
    activity types using `_type__in`.

    When listing [Custom Activities](https://developer.close.com/api/resources/activities/custom-activities), `_type` and
    `_type__in` can include Custom Activity Type ids (e.g. `actitype_1h5m6uHM9BZOpwVhyRJb4Y`) to filter by a specific custom
    activity type or `Custom` to list custom activities of any type.

    The following filtering parameters can only be used for listing activities on a single lead (using the `lead_id`
    parameter): `user_id`, `user_id__in`, `contact_id`, `contact_id__in`, `_type`, `_type__in`.

    All activities have two sortable datetime fields: `date_created` and `activity_at`. `date_created` denotes when an
    activity was created or synced into Close and `activity_at` denotes when that activity actually occurred. For example,
    on outgoing Email activities, `date_created` is equal to when the email was first created in Close, and `activity_at` is
    equal to when the email was actually sent. For Meeting activities, `activity_at` is equal to the scheduled time of the
    meeting. On custom activities, users are able to update the `activity_at` field at any time.

    Sorting by `-activity_at` can only be used when listing activities on a single lead using the `lead_id` parameter. In
    addition, you can only use the date-based filters of the field you're currently sorting on. This means that if you want
    to use `activity_at__lt` and `activity_at__gt` as filters, you need to include `_order_by=-activity_at` in your request.

    `thread_emails` parameter:

     - (Default) when this parameter is not present, `Email` objects will be returned for each email message.
     - A value of `true` will return `EmailThread` objects representing email conversations. Stripped-down version of
    `Email` objects will also be returned.
     - A value of `only` will return `EmailThread` objects representing email conversations. `Email` objects will not be
    returned.
    '''
    # handler for activities_list: GET /activity/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "activity/")
    page_info = _r.PageParams(
        max_count=_max_count,
        page_size_name="_limit",
        page_size_value=_limit,
        item_start_name="_skip",
        item_start_value=_skip,
    )
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if _limit is not None:
        params["_limit"] = _limit
    if _skip is not None:
        params["_skip"] = _skip
    if id_in is not None:
        params["id__in"] = id_in
    if lead_id is not None:
        params["lead_id"] = lead_id
    if contact_id is not None:
        params["contact_id"] = contact_id
    if user_id is not None:
        params["user_id"] = user_id
    if organization_id is not None:
        params["organization_id"] = organization_id
    if _type is not None:
        params["_type"] = _type
    if date_created_gte is not None:
        params["date_created__gte"] = date_created_gte
    if date_created_lte is not None:
        params["date_created__lte"] = date_created_lte
    if date_created_gt is not None:
        params["date_created__gt"] = date_created_gt
    if date_created_lt is not None:
        params["date_created__lt"] = date_created_lt
    if activity_at_gte is not None:
        params["activity_at__gte"] = activity_at_gte
    if activity_at_lte is not None:
        params["activity_at__lte"] = activity_at_lte
    if activity_at_gt is not None:
        params["activity_at__gt"] = activity_at_gt
    if activity_at_lt is not None:
        params["activity_at__lt"] = activity_at_lt
    if lead_id_in is not None:
        params["lead_id__in"] = lead_id_in
    if user_id_in is not None:
        params["user_id__in"] = user_id_in
    if contact_id_in is not None:
        params["contact_id__in"] = contact_id_in
    if _type_in is not None:
        params["_type__in"] = _type_in
    if _fields is not None:
        params["_fields"] = _fields
    if _order_by is not None:
        params["_order_by"] = _order_by

    try:
        data = _r.depaginate(page_info, url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)


if __name__ == "__main__":
    app()
