#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated

import typer
from rich_objects import display

from close_cli import _arguments as _a
from close_cli import _display as _d  # noqa: F401
from close_cli import _exceptions as _e
from close_cli import _logging as _l
from close_cli import _requests as _r
from close_cli import _tree as _t

app = typer.Typer(no_args_is_help=True, help="Manage bulk-action edit")


@app.command("commands", short_help="Display commands tree for edit sub-commands")
def show_commands(
    display_opt: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show edit sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "bulk_action_edit", display_opt, depth, search)


@app.command("create", short_help="Initiate a new bulk edit")
def bulk_actions_edit_create(
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Pass additional parameters depending on which `type` is passed:

     - `set_lead_status` will set the Lead Status on all leads. It expects:
      - `lead_status_id` - ID of the Lead Status to use.
     - `clear_custom_field` will clear/remove/unset a specific custom field from all leads. It expects:
      - `custom_field_id` or `custom_field_name` - ID or exact name of the custom field to remove.
     - `set_custom_field` will set/update/add a specific custom field on all leads. It expects:
      - `custom_field_id` or `custom_field_name` - ID or exact name of the custom field to set/update.
      - `custom_field_value` - New value. Use `custom_field_values` to pass multiple values to custom fields that support
    it.
      - `custom_field_operation` - `replace`, `add`, or `remove` (defaults to `replace`). Only applicable for custom fields
    that accept multiple values.

    Use `"send_done_email": false` if you don't want to get a confirmation email after the bulk action is done.
    '''
    # handler for bulk_actions.edit_create: POST /bulk_action/edit/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "bulk_action/edit/")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("POST", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)


@app.command("list", short_help="List bulk edits")
def bulk_actions_edit_list(
    _limit: Annotated[int | None, typer.Option(help="Number of results to return.")] = 100,
    _skip: Annotated[int | None, typer.Option(help="Number of results to skip before returning, for pagination.")] = 0,
    _fields: Annotated[str | None, typer.Option(show_default=False, help="Comma-separated list of fields to include in the response.")] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
    _max_count: _a.MaxCountOption = None,
) -> None:
    '''
    List bulk edits
    '''
    # handler for bulk_actions.edit_list: GET /bulk_action/edit/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "bulk_action/edit/")
    page_info = _r.PageParams(
        max_count=_max_count,
        page_size_name="_limit",
        page_size_value=_limit,
        item_start_name="_skip",
        item_start_value=_skip,
    )
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if _limit is not None:
        params["_limit"] = _limit
    if _skip is not None:
        params["_skip"] = _skip
    if _fields is not None:
        params["_fields"] = _fields

    try:
        data = _r.depaginate(page_info, url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)


@app.command("show", short_help="Fetch a single bulk edit object")
def bulk_actions_edit_get(
    id: Annotated[str, typer.Argument(show_default=False)],
    _fields: Annotated[str | None, typer.Option(show_default=False, help="Comma-separated list of fields to include in the response.")] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Fetch a single bulk edit object
    '''
    # handler for bulk_actions.edit_get: GET /bulk_action/edit/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "bulk_action/edit", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if _fields is not None:
        params["_fields"] = _fields

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)


if __name__ == "__main__":
    app()
