#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated  # noqa: F401

import typer
from rich_objects import display  # noqa: F401

from close_cli import _arguments as _a
from close_cli import _display as _d  # noqa: F401
from close_cli import _exceptions as _e  # noqa: F401
from close_cli import _logging as _l  # noqa: F401
from close_cli import _requests as _r  # noqa: F401
from close_cli import _tree as _t

app = typer.Typer(no_args_is_help=True, help="Manage bulk-action sequence-subscription")


@app.command("commands", short_help="Display commands tree for sequence-subscription sub-commands")
def show_commands(
    display_opt: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show sequence-subscription sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "bulk_action_sequence_subscription", display_opt, depth, search)
    return


@app.command("create", short_help="Initiate a new bulk sequence subscription")
def bulk_actions_sequence_subscriptions_create(
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    `action_type` must be one of:

    - `subscribe` to create a new sequence subscription for contacts that have never received the given sequence.
    - `resume` to resume any paused sequence subscriptions for the given sequence or all sequences if `sequence_id` is not
    provided.
    - `resume_finished` to resume any finished sequence subscriptions for the given sequence or all sequences if
    `sequence_id` is not provided.
    - `pause` to pause any active sequence subscriptions for the given sequence or all sequences if `sequence_id` is not
    provided.

    `sequence_id`, `sender_account_id`, `sender_name`, `sender_email` and `contact_preference` are required if `action_type`
    is `subscribe`.

    `contact_preference` can be set to:

    - `lead` to only subscribe the primary/first contact email of the lead.
    - `contact` to subscribe the primary email of each contact of the lead.

    `subscribe`, `resume` and `resume_finished` all start or restart Workflow
    runs, so they require a plan that includes them and otherwise return a 400.
    `pause` and `reassign` remain available on every plan.
    '''
    # handler for bulk_actions.sequence_subscriptions_create: POST /bulk_action/sequence_subscription/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "bulk_action/sequence_subscription/")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("POST", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("list", short_help="List bulk sequence subscriptions")
def bulk_actions_sequence_subscriptions_list(
    _limit: Annotated[int | None, typer.Option(help="Number of results to return.")] = 100,
    _skip: Annotated[int | None, typer.Option(help="Number of results to skip before returning, for pagination.")] = 0,
    _fields: Annotated[str | None, typer.Option(show_default=False, help="Comma-separated list of fields to include in the response.")] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
    _max_count: _a.MaxCountOption = None,
) -> None:
    '''
    List bulk sequence subscriptions
    '''
    # handler for bulk_actions.sequence_subscriptions_list: GET /bulk_action/sequence_subscription/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "bulk_action/sequence_subscription/")
    page_info = _r.PageParams(
        max_count=_max_count,
        page_size_name="_limit",
        page_size_value=_limit,
        item_start_name="_skip",
        item_start_value=_skip,
    )
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if _limit is not None:
        params["_limit"] = _limit
    if _skip is not None:
        params["_skip"] = _skip
    if _fields is not None:
        params["_fields"] = _fields

    try:
        data = _r.depaginate(page_info, url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("show", short_help="Fetch a single bulk sequence subscription object")
def bulk_actions_sequence_subscriptions_get(
    id: Annotated[str, typer.Argument(show_default=False)],
    _fields: Annotated[str | None, typer.Option(show_default=False, help="Comma-separated list of fields to include in the response.")] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Fetch a single bulk sequence subscription object
    '''
    # handler for bulk_actions.sequence_subscriptions_get: GET /bulk_action/sequence_subscription/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "bulk_action/sequence_subscription", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if _fields is not None:
        params["_fields"] = _fields

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


if __name__ == "__main__":
    app()
