#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated  # noqa: F401

import typer
from rich_objects import display  # noqa: F401

from close_cli import _arguments as _a
from close_cli import _display as _d  # noqa: F401
from close_cli import _exceptions as _e  # noqa: F401
from close_cli import _logging as _l  # noqa: F401
from close_cli import _requests as _r  # noqa: F401
from close_cli import _tree as _t

app = typer.Typer(no_args_is_help=True, help="Manage connected-account")


@app.command("commands", short_help="Display commands tree for connected-account sub-commands")
def show_commands(
    display_opt: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show connected-account sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "connected_account", display_opt, depth, search)
    return


@app.command("list", short_help="List connected accounts")
def connected_accounts_list(
    _fields: Annotated[list[str] | None, typer.Option()] = ["_type", "available_calendars", "available_features", "calendar_receive_status", "calendly", "date_created", "default_identity", "email", "email_receive_status", "enabled_features", "has_meeting_creation_scopes", "id", "identities", "imap", "is_imap_archive_sync_enabled", "label", "latest_receive_error", "latest_send_error", "lead_suggestions_updated_at", "organization_id", "receive_status", "send_status", "smtp", "sync_all_calendars", "synced_calendars", "user_id", "zoom_account_plan"],
    user_id: Annotated[str | None, typer.Option(show_default=False)] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    You can filter down to a specific user by passing the `?user_id` query parameter.
    '''
    # handler for connected_accounts_list: GET /connected_account/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "connected_account/")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if _fields is not None:
        params["_fields"] = _fields
    if user_id is not None:
        params["user_id"] = user_id

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("show", short_help="Fetch a single connected account")
def connected_accounts_get(
    id: Annotated[str, typer.Argument(show_default=False)],
    _fields: Annotated[list[str] | None, typer.Option()] = ["_type", "available_calendars", "available_features", "calendar_receive_status", "calendly", "date_created", "default_identity", "email", "email_receive_status", "enabled_features", "has_meeting_creation_scopes", "id", "identities", "imap", "is_imap_archive_sync_enabled", "label", "latest_receive_error", "latest_send_error", "lead_suggestions_updated_at", "organization_id", "receive_status", "send_status", "smtp", "sync_all_calendars", "synced_calendars", "user_id", "zoom_account_plan"],
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Fetch a single connected account
    '''
    # handler for connected_accounts_get: GET /connected_account/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "connected_account", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if _fields is not None:
        params["_fields"] = _fields

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


if __name__ == "__main__":
    app()
