#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated  # noqa: F401

import typer
from rich_objects import display  # noqa: F401

from close_cli import _arguments as _a
from close_cli import _display as _d  # noqa: F401
from close_cli import _exceptions as _e  # noqa: F401
from close_cli import _logging as _l  # noqa: F401
from close_cli import _requests as _r  # noqa: F401
from close_cli import _tree as _t

app = typer.Typer(no_args_is_help=True, help="Manage dialer")


@app.command("commands", short_help="Display commands tree for dialer sub-commands")
def show_commands(
    display_opt: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show dialer sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "dialer", display_opt, depth, search)


class SourceType(str, Enum):  # noqa: F811
    SAVED_SEARCH = "saved-search"
    SHARED_ENTRY = "shared-entry"


@app.command("list", short_help="List or filter all dialer sessions")
def dialers_list(
    organization_id: Annotated[str | None, typer.Option(show_default=False)] = None,
    source_type: Annotated[SourceType | None, typer.Option(show_default=False, case_sensitive=False)] = None,
    source_value: Annotated[str | None, typer.Option(show_default=False)] = None,
    status: Annotated[str | None, typer.Option(show_default=False)] = None,
    status_in: Annotated[str | None, typer.Option(show_default=False)] = None,
    user_id: Annotated[str | None, typer.Option(show_default=False)] = None,
    _limit: Annotated[int | None, typer.Option(help="Number of results to return.")] = 100,
    _skip: Annotated[int | None, typer.Option(help="Number of results to skip before returning, for pagination.")] = 0,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
    _max_count: _a.MaxCountOption = None,
) -> None:
    '''
    List or filter all dialer sessions
    '''
    # handler for dialers_list: GET /dialer/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "dialer/")
    page_info = _r.PageParams(
        max_count=_max_count,
        page_size_name="_limit",
        page_size_value=_limit,
        item_start_name="_skip",
        item_start_value=_skip,
    )
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if organization_id is not None:
        params["organization_id"] = organization_id
    if source_type is not None:
        params["source_type"] = source_type
    if source_value is not None:
        params["source_value"] = source_value
    if status is not None:
        params["status"] = status
    if status_in is not None:
        params["status__in"] = status_in
    if user_id is not None:
        params["user_id"] = user_id
    if _limit is not None:
        params["_limit"] = _limit
    if _skip is not None:
        params["_skip"] = _skip

    try:
        data = _r.depaginate(page_info, url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)


@app.command("show", short_help="Get a single dialer session")
def dialers_get(
    id: Annotated[str, typer.Argument(show_default=False)],
    organization_id: Annotated[str | None, typer.Option(show_default=False)] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Once you have a `source_value` for a dialer session and `source_type=saved-search`, you can use the [saved_search
    endpoint](https://developer.close.com/api/resources/smart-views/get) to find out more information about the Smart View
    being used.
    '''
    # handler for dialers_get: GET /dialer/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "dialer", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if organization_id is not None:
        params["organization_id"] = organization_id

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)


if __name__ == "__main__":
    app()
