#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated

import typer
from rich_objects import display

from close_cli import _arguments as _a
from close_cli import _display as _d  # noqa: F401
from close_cli import _exceptions as _e
from close_cli import _logging as _l
from close_cli import _requests as _r
from close_cli import _tree as _t

app = typer.Typer(no_args_is_help=True, help="Manage form")


@app.command("commands", short_help="Display commands tree for form sub-commands")
def show_commands(
    display_opt: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show form sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "form", display_opt, depth, search)


@app.command("list", short_help="List Forms")
def forms_list(
    _limit: Annotated[int | None, typer.Option(help="Number of results to return.")] = 100,
    _skip: Annotated[int | None, typer.Option(help="Number of results to skip before returning, for pagination.")] = 0,
    is_archived: Annotated[bool | None, typer.Option("--is-archived/--no-is-archived", show_default=False, help="Filter by archive status.")] = None,
    _fields: Annotated[str | None, typer.Option(show_default=False, help="Comma-separated list of fields to include in the response.")] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
    _max_count: _a.MaxCountOption = None,
) -> None:
    '''
    List all forms and their published field definitions for your organization.
    '''
    # handler for forms_list: GET /form/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "form/")
    page_info = _r.PageParams(
        max_count=_max_count,
        page_size_name="_limit",
        page_size_value=_limit,
        item_start_name="_skip",
        item_start_value=_skip,
    )
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if _limit is not None:
        params["_limit"] = _limit
    if _skip is not None:
        params["_skip"] = _skip
    if is_archived is not None:
        params["is_archived"] = is_archived
    if _fields is not None:
        params["_fields"] = _fields

    try:
        data = _r.depaginate(page_info, url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)


@app.command("show", short_help="Retrieve a Form")
def forms_fetch(
    id: Annotated[str, typer.Argument(show_default=False)],
    _fields: Annotated[str | None, typer.Option(show_default=False, help="Comma-separated list of fields to include in the response.")] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Retrieve a single form and its published field definitions by ID.
    '''
    # handler for forms_fetch: GET /form/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "form", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if _fields is not None:
        params["_fields"] = _fields

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)


if __name__ == "__main__":
    app()
