#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated  # noqa: F401

import typer
from rich_objects import display  # noqa: F401

from close_cli import _arguments as _a
from close_cli import _display as _d  # noqa: F401
from close_cli import _exceptions as _e  # noqa: F401
from close_cli import _logging as _l  # noqa: F401
from close_cli import _requests as _r  # noqa: F401
from close_cli import _tree as _t

app = typer.Typer(no_args_is_help=True, help="Manage integration-link")


@app.command("commands", short_help="Display commands tree for integration-link sub-commands")
def show_commands(
    display_opt: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show integration-link sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "integration_link", display_opt, depth, search)
    return


class IntegrationLinkType(str, Enum):  # noqa: F811
    LEAD = "lead"
    CONTACT = "contact"
    OPPORTUNITY = "opportunity"


@app.command("create", short_help="Create an integration link")
def integration_links_create(
    name: Annotated[str, typer.Option(show_default=False)] = None,
    type_: Annotated[IntegrationLinkType, typer.Option("--type", show_default=False, case_sensitive=False)] = None,
    url: Annotated[str, typer.Option(show_default=False)] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Create an integration link
    '''
    # handler for integration_links_create: POST /integration_link/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "integration_link/")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if name is None:
        missing.append("--name")
    if type_ is None:
        missing.append("--type")
    if url is None:
        missing.append("--url")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    body = {}
    body["name"] = name
    body["type"] = type_
    body["url"] = url

    try:
        data = _r.request("POST", url, headers=headers, params=params, body=body, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("delete", short_help="Delete an integration link")
def integration_links_delete(
    id: Annotated[str, typer.Argument(show_default=False)],
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Delete an integration link
    '''
    # handler for integration_links_delete: DELETE /integration_link/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "integration_link", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("DELETE", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("list", short_help="Get all integration links for your organization")
def integration_links_list(
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Get all integration links for your organization
    '''
    # handler for integration_links_list: GET /integration_link/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "integration_link/")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


class IntegrationLinkType(str, Enum):  # noqa: F811
    LEAD = "lead"
    CONTACT = "contact"
    OPPORTUNITY = "opportunity"


@app.command("set", short_help="Update an integration link")
def integration_links_update(
    id: Annotated[str, typer.Argument(show_default=False)],
    name: Annotated[str | None, typer.Option(show_default=False)] = None,
    type_: Annotated[IntegrationLinkType | None, typer.Option("--type", show_default=False, case_sensitive=False)] = None,
    url: Annotated[str | None, typer.Option(show_default=False)] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Update an integration link
    '''
    # handler for integration_links_update: PUT /integration_link/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "integration_link", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    body = {}
    if name is not None:
        body["name"] = name
    if type_ is not None:
        body["type"] = type_
    if url is not None:
        body["url"] = url

    try:
        data = _r.request("PUT", url, headers=headers, params=params, body=body, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("show", short_help="Get a single integration link")
def integration_links_get(
    id: Annotated[str, typer.Argument(show_default=False)],
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Get a single integration link
    '''
    # handler for integration_links_get: GET /integration_link/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "integration_link", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


if __name__ == "__main__":
    app()
