#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated  # noqa: F401

import typer
from rich_objects import display  # noqa: F401

from close_cli import _arguments as _a
from close_cli import _display as _d  # noqa: F401
from close_cli import _exceptions as _e  # noqa: F401
from close_cli import _logging as _l  # noqa: F401
from close_cli import _requests as _r  # noqa: F401
from close_cli import _tree as _t
from close_cli.membership_pinned_views import app as membership_pinned_views

app = typer.Typer(no_args_is_help=True, help="Manage membership")
app.add_typer(membership_pinned_views, name="pinned-views")


@app.command("commands", short_help="Display commands tree for membership sub-commands")
def show_commands(
    display_opt: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show membership sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "membership", display_opt, depth, search)
    return


@app.command("create", short_help="Create a membership")
def memberships_create(
    email: Annotated[str, typer.Option(show_default=False)] = None,
    role_id: Annotated[str, typer.Option(show_default=False, help="One of `superuser`, `user`, or `restricteduser` for the corresponding predefined role, or the ID of a custom [Role](https://developer.close.com/api/resources/roles). The role must not grant the `manage_organization` permission.")] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Ensures an active membership for the given email will be provisioned.

    - If the user already exists, they will be added to the requestor's organization.
    - If it doesn't exist, a new user will be provisioned.

    This request requires "Manage Organization" permissions.

    As a security precaution, this operation requires the organization to have the
    "Restrict new users to emails from these domains" setting enabled, and the new
    member's email address must belong to one of its verified domains.
    '''
    # handler for memberships_create: POST /membership/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "membership/")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if email is None:
        missing.append("--email")
    if role_id is None:
        missing.append("--role-id")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    body = {}
    body["email"] = email
    body["role_id"] = role_id

    try:
        data = _r.request("POST", url, headers=headers, params=params, body=body, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("delete", short_help="Delete a membership")
def memberships_delete(
    id: Annotated[str, typer.Argument(show_default=False)],
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Deactivates a membership, removing the user from the associated organization.
    '''
    # handler for memberships_delete: DELETE /membership/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "membership", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("DELETE", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


class AutoRecordCalls(str, Enum):  # noqa: F811
    ENABLED = "enabled"
    DISABLED = "disabled"
    UNSET = "unset"


class CallerIdMode(str, Enum):  # noqa: F811
    FIXED = "fixed"
    AUTO = "auto"


@app.command("set", short_help="Update a membership")
def memberships_update(
    id: Annotated[str, typer.Argument(show_default=False)],
    auto_record_calls: Annotated[AutoRecordCalls | None, typer.Option(show_default=False, case_sensitive=False, help="Whether this member\'s calls are automatically recorded. Starts as `unset` and can be set to `enabled` or `disabled`.")] = None,
    default_caller_id: Annotated[str | None, typer.Option(show_default=False, help="ID of the phone number to use as this member\'s default outbound caller ID. Close keeps this value while `default_caller_id_mode` is `auto`, but outbound calls do not use it.")] = None,
    default_caller_id_mode: Annotated[CallerIdMode | None, typer.Option(show_default=False, case_sensitive=False, help="How a caller\'s outbound number is chosen. Fixed uses a single configured number; Auto lets Close select the best number per call/SMS (Managed by Close Caller ID).")] = None,
    hangup_recording_url: Annotated[str | None, typer.Option(show_default=False, help="URL of the audio file used as this member\'s voicemail drop recording.")] = None,
    may_workflows_impersonate: Annotated[bool | None, typer.Option("--may-workflows-impersonate/--no-may-workflows-impersonate", show_default=False, help="Whether Workflows may send emails on this member\'s behalf.")] = None,
    role_id: Annotated[str | None, typer.Option(show_default=False, help="One of `admin`, `superuser`, `user`, or `restricteduser` for the corresponding predefined role, or the ID of a custom [Role](https://developer.close.com/api/resources/roles).")] = None,
    track_email_opens: Annotated[bool | None, typer.Option("--track-email-opens/--no-track-email-opens", show_default=False, help="Whether email opens are tracked for emails this member sends.")] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Update a membership
    '''
    # handler for memberships_update: PUT /membership/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "membership", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    body = {}
    if auto_record_calls is not None:
        body["auto_record_calls"] = auto_record_calls
    if default_caller_id is not None:
        body["default_caller_id"] = default_caller_id
    if default_caller_id_mode is not None:
        body["default_caller_id_mode"] = default_caller_id_mode
    if hangup_recording_url is not None:
        body["hangup_recording_url"] = hangup_recording_url
    if may_workflows_impersonate is not None:
        body["may_workflows_impersonate"] = may_workflows_impersonate
    if role_id is not None:
        body["role_id"] = role_id
    if track_email_opens is not None:
        body["track_email_opens"] = track_email_opens

    try:
        data = _r.request("PUT", url, headers=headers, params=params, body=body, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


class AutoRecordCalls(str, Enum):  # noqa: F811
    ENABLED = "enabled"
    DISABLED = "disabled"
    UNSET = "unset"


class CallerIdMode(str, Enum):  # noqa: F811
    FIXED = "fixed"
    AUTO = "auto"


@app.command("set-many", short_help="Bulk update memberships")
def memberships_bulk_update(
    auto_record_calls: Annotated[AutoRecordCalls | None, typer.Option(show_default=False, case_sensitive=False, help="Whether this member\'s calls are automatically recorded. Starts as `unset` and can be set to `enabled` or `disabled`.")] = None,
    default_caller_id: Annotated[str | None, typer.Option(show_default=False, help="ID of the phone number to use as this member\'s default outbound caller ID. Close keeps this value while `default_caller_id_mode` is `auto`, but outbound calls do not use it.")] = None,
    default_caller_id_mode: Annotated[CallerIdMode | None, typer.Option(show_default=False, case_sensitive=False, help="How a caller\'s outbound number is chosen. Fixed uses a single configured number; Auto lets Close select the best number per call/SMS (Managed by Close Caller ID).")] = None,
    hangup_recording_url: Annotated[str | None, typer.Option(show_default=False, help="URL of the audio file used as this member\'s voicemail drop recording.")] = None,
    may_workflows_impersonate: Annotated[bool | None, typer.Option("--may-workflows-impersonate/--no-may-workflows-impersonate", show_default=False, help="Whether Workflows may send emails on this member\'s behalf.")] = None,
    role_id: Annotated[str | None, typer.Option(show_default=False, help="One of `admin`, `superuser`, `user`, or `restricteduser` for the corresponding predefined role, or the ID of a custom [Role](https://developer.close.com/api/resources/roles).")] = None,
    track_email_opens: Annotated[bool | None, typer.Option("--track-email-opens/--no-track-email-opens", show_default=False, help="Whether email opens are tracked for emails this member sends.")] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Any field that can be updated on a membership individually can also be used to bulk update multiple memberships. Pass
    the comma-separated ids of the memberships to update into `id__in` in `_params`. For example:

    ```json
    {"_params": {"id__in": "memb_A,memb_B"}, "role_id": "role_y6eLquXvRUdmwqi61tsmgCJUU7uGfxaRbDuLoONZL9p"}
    ```
    '''
    # handler for memberships_bulk_update: PUT /membership/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "membership/")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    body = {}
    if auto_record_calls is not None:
        body["auto_record_calls"] = auto_record_calls
    if default_caller_id is not None:
        body["default_caller_id"] = default_caller_id
    if default_caller_id_mode is not None:
        body["default_caller_id_mode"] = default_caller_id_mode
    if hangup_recording_url is not None:
        body["hangup_recording_url"] = hangup_recording_url
    if may_workflows_impersonate is not None:
        body["may_workflows_impersonate"] = may_workflows_impersonate
    if role_id is not None:
        body["role_id"] = role_id
    if track_email_opens is not None:
        body["track_email_opens"] = track_email_opens

    try:
        data = _r.request("PUT", url, headers=headers, params=params, body=body, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


if __name__ == "__main__":
    app()
