#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated  # noqa: F401

import typer
from rich_objects import display  # noqa: F401

from close_cli import _arguments as _a
from close_cli import _display as _d  # noqa: F401
from close_cli import _exceptions as _e  # noqa: F401
from close_cli import _logging as _l  # noqa: F401
from close_cli import _requests as _r  # noqa: F401
from close_cli import _tree as _t

app = typer.Typer(no_args_is_help=True, help="Manage organization")


@app.command("commands", short_help="Display commands tree for organization sub-commands")
def show_commands(
    display_opt: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show organization sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "organization", display_opt, depth, search)


@app.command("set", short_help="Update an organization")
def organizations_update(
    id: Annotated[str, typer.Argument(show_default=False)],
    _expand: Annotated[str | None, typer.Option(show_default=False)] = None,
    currency: Annotated[str | None, typer.Option(show_default=False, help="Default currency as a three-letter [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) currency code.")] = None,
    enable_unsubscribe_link: Annotated[bool | None, typer.Option("--enable-unsubscribe-link/--no-enable-unsubscribe-link", show_default=False, help="Enable the unsubscribe link by default in new email templates.")] = None,
    lead_statuses_id: Annotated[str | None, typer.Option(show_default=False, help="ID of an existing lead status.")] = None,
    lead_statuses_label: Annotated[str | None, typer.Option(show_default=False, help="Label of the lead status.")] = None,
    name: Annotated[str | None, typer.Option(show_default=False, help="The organization\'s name.")] = None,
    require_unsubscribe_link: Annotated[bool | None, typer.Option("--require-unsubscribe-link/--no-require-unsubscribe-link", show_default=False, help="Require an unsubscribe link in Bulk Emails and Workflows.")] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Update an organization
    '''
    # handler for organizations_update: PUT /organization/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "organization", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if _expand is not None:
        params["_expand"] = _expand
    body = {}
    lead_statuses = {}
    if currency is not None:
        body["currency"] = currency
    if enable_unsubscribe_link is not None:
        body["enable_unsubscribe_link"] = enable_unsubscribe_link
    if lead_statuses_id is not None:
        lead_statuses["id"] = lead_statuses_id
    if lead_statuses_label is not None:
        lead_statuses["label"] = lead_statuses_label
    if name is not None:
        body["name"] = name
    if require_unsubscribe_link is not None:
        body["require_unsubscribe_link"] = require_unsubscribe_link
    # stitch together the sub-objects
    if lead_statuses:
        body["lead_statuses"] = [lead_statuses]  # convert to list

    try:
        data = _r.request("PUT", url, headers=headers, params=params, body=body, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)


@app.command("show", short_help="Get an organization\'s details")
def organizations_get(
    id: Annotated[str, typer.Argument(show_default=False)],
    _expand: Annotated[str | None, typer.Option(show_default=False)] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    By default, `memberships` and `inactive_memberships` are populated with user data prefixed with `user_`. If you'd rather
    have a nested `user` field, use a query string like `?_expand=memberships__user,inactive_memberships__user`.
    '''
    # handler for organizations_get: GET /organization/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "organization", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if _expand is not None:
        params["_expand"] = _expand

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)


if __name__ == "__main__":
    app()
