#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated

import typer
from rich_objects import display

from close_cli import _arguments as _a
from close_cli import _display as _d  # noqa: F401
from close_cli import _exceptions as _e
from close_cli import _logging as _l
from close_cli import _requests as _r
from close_cli import _tree as _t

app = typer.Typer(no_args_is_help=True, help="Manage phone-number request")


@app.command("commands", short_help="Display commands tree for request sub-commands")
def show_commands(
    display_opt: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show request sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "phone_number_request", display_opt, depth, search)


class CarrierType(str, Enum):  # noqa: F811
    LOCAL = "local"
    NATIONAL = "national"
    MOBILE = "mobile"
    TOLLFREE = "tollfree"


class PhoneNumberSharing(str, Enum):  # noqa: F811
    PERSONAL = "personal"
    GROUP = "group"


@app.command("internal", short_help="Request an internal phone number")
def phone_numbers_create(
    bundle_id: Annotated[str | None, typer.Option(show_default=False)] = None,
    carrier_type: Annotated[CarrierType | None, typer.Option(show_default=False, case_sensitive=False)] = None,
    country: Annotated[str, typer.Option(show_default=False, help="A two letter ISO country code (e.g. `US` for United States).")] = None,
    prefix: Annotated[str | None, typer.Option(help="A string with the phone number prefix or area code, not including the country code.")] = "",
    sharing: Annotated[PhoneNumberSharing | None, typer.Option(case_sensitive=False, hidden=True, help="Deprecated. `personal` for a number that belongs to an individual user, or `group` for a group number. The distinction between personal and group numbers is being removed, and this field will be removed in a future update. When omitted, defaults to `personal`.")] = "personal",
    with_mms: Annotated[bool | None, typer.Option("--with-mms/--no-with-mms", show_default=False, help="By default, MMS-capable numbers are rented if Close supports MMS for the given country. Renting an MMS-capable number can be forced by setting this flag to `true`. If set to `false`, certain prefixes that don\'t support MMS can be rented in countries where Close supports MMS. In most scenarios, this flag should not be passed. When you request an MMS number, you must set `with_sms` to `true` as well.")] = None,
    with_sms: Annotated[bool | None, typer.Option("--with-sms/--no-with-sms", show_default=False, help="By default, SMS-capable numbers are rented if Close supports SMS for the given country. Renting an SMS-capable number can be forced by setting this flag to `true`. If set to `false`, certain prefixes that don\'t support SMS can be rented in countries where Close supports SMS. In most scenarios, this flag should not be passed unless a `has-voice-only` error status is received.")] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Renting a phone number incurs a cost. You need the "Manage Team Phone Numbers" permission to rent group numbers.

    If a number was rented, a 201 response is returned with the new number. If no number was rented (4xx response code), the
    response contains a `status` field which may contain one of the values below. New statuses may be added in the future.

    * `has-voice-only`: This country/prefix combination only has non-SMS-capable
      numbers. You can attempt renting the number by passing `with_sms` as `false`.
    * `needs-more-info`: More information (such as proof of address) is needed to
      rent this number. This number can only be rented by contacting Close support.
    * `billing-error`: An error related to billing has occurred. For example, the
      telephony budget has been reached, or there are not enough funds and recharging failed.
    * `error`: An error has occurred while renting this number. A human-readable
      message is returned in the `error` field.
    '''
    # handler for phone_numbers_create: POST /phone_number/request/internal/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "phone_number/request/internal/")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if country is None:
        missing.append("--country")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    body = {}
    if bundle_id is not None:
        body["bundle_id"] = bundle_id
    if carrier_type is not None:
        body["carrier_type"] = carrier_type
    body["country"] = country
    if prefix is not None:
        body["prefix"] = prefix
    if sharing is not None:
        _l.logger().warning("--sharing is deprecated and should not be used")
        body["sharing"] = sharing
    if with_mms is not None:
        body["with_mms"] = with_mms
    if with_sms is not None:
        body["with_sms"] = with_sms

    try:
        data = _r.request("POST", url, headers=headers, params=params, body=body, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)


if __name__ == "__main__":
    app()
