#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated  # noqa: F401

import typer
from rich_objects import display  # noqa: F401

from close_cli import _arguments as _a
from close_cli import _display as _d  # noqa: F401
from close_cli import _exceptions as _e  # noqa: F401
from close_cli import _logging as _l  # noqa: F401
from close_cli import _requests as _r  # noqa: F401
from close_cli import _tree as _t
from close_cli.phone_number_request import app as phone_number_request

app = typer.Typer(no_args_is_help=True, help="Manage phone-number")
app.add_typer(phone_number_request, name="request")


@app.command("commands", short_help="Display commands tree for phone-number sub-commands")
def show_commands(
    display_opt: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show phone-number sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "phone_number", display_opt, depth, search)
    return


@app.command("delete", short_help="Delete a phone number")
def phone_numbers_delete(
    id: Annotated[str, typer.Argument(show_default=False)],
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    You need the "Manage Team Phone Numbers" permission to delete a group number. You can only delete your own personal
    numbers.
    '''
    # handler for phone_numbers_delete: DELETE /phone_number/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "phone_number", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("DELETE", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("list", short_help="List or search for phone numbers")
def phone_numbers_list(
    _limit: Annotated[int | None, typer.Option(help="Number of results to return.")] = 100,
    _skip: Annotated[int | None, typer.Option(help="Number of results to skip before returning, for pagination.")] = 0,
    _fields: Annotated[str | None, typer.Option(show_default=False, help="Comma-separated list of fields to include in the response.")] = None,
    number: Annotated[str | None, typer.Option(show_default=False)] = None,
    user_id: Annotated[str | None, typer.Option(show_default=False, hidden=True, help="Deprecated. Use `participant_user_id` instead. The distinction between personal and group numbers is being removed, and `user_id` will be removed in a future update.")] = None,
    is_group_number: Annotated[bool | None, typer.Option("--is-group-number/--no-is-group-number", show_default=False, hidden=True, help="Deprecated. Use `participant_user_id` instead. The distinction between personal and group numbers is being removed, and `is_group_number` will be removed in a future update.")] = None,
    participant_user_id: Annotated[str | None, typer.Option(show_default=False, help="Return numbers the given user participates in, including both personal and group numbers they belong to.")] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
    _max_count: _a.MaxCountOption = None,
) -> None:
    '''
    List or search for phone numbers
    '''
    # handler for phone_numbers_list: GET /phone_number/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "phone_number/")
    page_info = _r.PageParams(
        max_count=_max_count,
        page_size_name="_limit",
        page_size_value=_limit,
        item_start_name="_skip",
        item_start_value=_skip,
    )
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if _limit is not None:
        params["_limit"] = _limit
    if _skip is not None:
        params["_skip"] = _skip
    if _fields is not None:
        params["_fields"] = _fields
    if number is not None:
        params["number"] = number
    if user_id is not None:
        _l.logger().warning("--user-id is deprecated")
        params["user_id"] = user_id
    if is_group_number is not None:
        _l.logger().warning("--is-group-number is deprecated")
        params["is_group_number"] = is_group_number
    if participant_user_id is not None:
        params["participant_user_id"] = participant_user_id

    try:
        data = _r.depaginate(page_info, url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("set", short_help="Update a phone number")
def phone_numbers_update(
    id: Annotated[str, typer.Argument(show_default=False)],
    forward_to: Annotated[str | None, typer.Option(show_default=False)] = None,
    forward_to_enabled: Annotated[bool | None, typer.Option("--forward-to-enabled/--no-forward-to-enabled", show_default=False)] = None,
    inbound_ring_duration: Annotated[int | None, typer.Option(min=15, max=90, show_default=False, help="Number of seconds (15-90) to ring this number on inbound calls before moving on (e.g. to voicemail).")] = None,
    label: Annotated[str | None, typer.Option(show_default=False)] = None,
    participants: Annotated[list[str] | None, typer.Option(show_default=False)] = None,
    phone_numbers: Annotated[list[str] | None, typer.Option(show_default=False)] = None,
    press_1_to_accept: Annotated[bool | None, typer.Option("--press-1-to-accept/--no-press-1-to-accept", show_default=False)] = None,
    voicemail_greeting_url: Annotated[str | None, typer.Option(show_default=False)] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    You need the "Manage Team Phone Numbers" permission to update a group number. You can only update your own personal
    numbers.

    You can:

    - Change a `label` of your number.
    - Set up call forwarding via `forward_to` and `forward_to_enabled`.
    - Set up a voicemail greeting by including a URL of an mp3 recording in `voicemail_greeting_url`. We require the URL to
    be secure (i.e. starting with https://).
    - Modify which team members are part of a group number via `participants`. This should be a list of user IDs.
    - Modify which external phone numbers are part of a group number via `phone_numbers`. This should be a list of phone
    numbers in E.164 international format, e.g. "+16503334444".
    - Change how long (in seconds, 15-90) the number rings on inbound calls before moving on (e.g. to voicemail) via
    `inbound_ring_duration`.
    '''
    # handler for phone_numbers_update: PUT /phone_number/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "phone_number", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    body = {}
    if forward_to is not None:
        body["forward_to"] = forward_to
    if forward_to_enabled is not None:
        body["forward_to_enabled"] = forward_to_enabled
    if inbound_ring_duration is not None:
        body["inbound_ring_duration"] = inbound_ring_duration
    if label is not None:
        body["label"] = label
    if participants is not None:
        body["participants"] = participants
    if phone_numbers is not None:
        body["phone_numbers"] = phone_numbers
    if press_1_to_accept is not None:
        body["press_1_to_accept"] = press_1_to_accept
    if voicemail_greeting_url is not None:
        body["voicemail_greeting_url"] = voicemail_greeting_url

    try:
        data = _r.request("PUT", url, headers=headers, params=params, body=body, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


@app.command("show", short_help="Retrieve a single phone number")
def phone_numbers_get(
    id: Annotated[str, typer.Argument(show_default=False)],
    _fields: Annotated[str | None, typer.Option(show_default=False, help="Comma-separated list of fields to include in the response.")] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Retrieve a single phone number
    '''
    # handler for phone_numbers_get: GET /phone_number/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "phone_number", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if _fields is not None:
        params["_fields"] = _fields

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)

    return


if __name__ == "__main__":
    app()
