#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated  # noqa: F401

import typer
from rich_objects import display  # noqa: F401

from close_cli import _arguments as _a
from close_cli import _display as _d  # noqa: F401
from close_cli import _exceptions as _e  # noqa: F401
from close_cli import _logging as _l  # noqa: F401
from close_cli import _requests as _r  # noqa: F401
from close_cli import _tree as _t

app = typer.Typer(no_args_is_help=True, help="Manage report funnel opportunity")


@app.command("commands", short_help="Display commands tree for opportunity sub-commands")
def show_commands(
    display_opt: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show opportunity sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "report_funnel_opportunity", display_opt, depth, search)


@app.command("stages", short_help="Get a funnel report (stages)")
def reporting_get_funnel_stages(
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    The opportunity funnel "stages" report returns the pipeline funnel's metrics for the selected opportunities, aggregated
    (JSON format only) and per-user (JSON and CSV formats).

    Every report accepts the following parameters:

    * `pipeline`: ID of the pipeline defining the funnel statuses.
    * `type`: the type of the report. The available values are `created-cohort` and `active-stage-cohort`.
    * `report_relative_range`: a relative time range to fetch data for. The allowed values are: `today`, `this-week`, `this-
    month`, `this-quarter`, `this-year`, `yesterday`, `last-week`, `last-month`, `last-quarter`, `last-year`, and `all-
    time`.
    * `report_datetime_range`: a time range to fetch data for.
    * `cohort_relative_range`: a relative time range defining the cohort of created opportunities to fetch data for, by date
    of creation of those opportunities. The allowed values are: `today`, `this-week`, `this-month`, `this-quarter`, `this-
    year`, `yesterday`, `last-week`, `last-month`, `last-quarter`, `last-year`, and `all-time`. Either this field or
    `cohort_datetime_range` needs to be specified for `created-cohort` reports. Its value will be ignored for `active-stage-
    cohort` reports.
    * `cohort_datetime_range`: a time range defining the cohort of created opportunities to fetch data for, by date of
    creation of those opportunities. Either this field or `cohort_relative_range` needs to be specified for `created-cohort`
    reports. Its value will be ignored for `active-stage-cohort` reports.
    * `compared_relative_range`: a relative time range to fetch comparison data for. Only allowed in combination with
    `report_relative_range` (for `active-stage-cohort` reports) or `cohort_relative_range` (for `created-cohort` reports).
    The allowed values are: `today`, `this-week`, `this-month`, `this-quarter`, `this-year`, `yesterday`, `last-week`,
    `last-month`, `last-quarter`, `last-year`, and `all-time`.
    * `compared_datetime_range`: a relative time range to fetch comparison data for. Only allowed in combination with
    `report_datetime_range` (for `active-stage-cohort` reports) or `cohort_datetime_range` (for `created-cohort` reports).
    The allowed values are: `same-days-last-week`, `same-days-last-month`, `same-days-last-quarter`, `same-days-last-year`.
    * `compared_custom_range`: a time range to fetch comparison data for.
    * `query`: a query to apply to the report to filter out data.
      The value of the field is a dictionary with the key `type` and any type-specific keys. For now only the type
    `saved_search` is allowed which takes the extra key `saved_search_id` to specify the ID of a saved search. This
    parameter is *optional*.
    * `users`: a list of user IDs or group IDs to limit the report results to. When it's empty, the report will include all
    the available users. This parameter is *optional*.

    The report can be requested either in JSON format or in CSV format. The format can be specified with the `accept`
    header.

    In JSON format, it includes aggregated and per-user data. When requested in CSV format, it includes only per-user data.

    When `compared_datetime_range`, `compared_relative_range`, or `compared_custom_range` are used, the report returned is
    the compared one, not the base one.
    '''
    # handler for reporting_get_funnel_stages: POST /report/funnel/opportunity/stages/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "report/funnel/opportunity/stages/")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("POST", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)


@app.command("totals", short_help="Get a funnel report (totals)")
def reporting_get_funnel_totals(
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    The opportunity funnel "totals" report returns the pipeline funnel's metrics for the selected opportunities, aggregated
    (JSON format only) and per-user (JSON and CSV formats).

    Every report accepts the following parameters:

    * `pipeline`: ID of the pipeline defining the funnel statuses.
    * `type`: the type of the report. The available values are `created-cohort` and `active-stage-cohort`.
    * `report_relative_range`: a relative time range to fetch data for. The allowed values are: `today`, `this-week`, `this-
    month`, `this-quarter`, `this-year`, `yesterday`, `last-week`, `last-month`, `last-quarter`, `last-year`, and `all-
    time`.
    * `report_datetime_range`: a time range to fetch data for.
    * `cohort_relative_range`: a relative time range defining the cohort of created opportunities to fetch data for, by date
    of creation of those opportunities. The allowed values are: `today`, `this-week`, `this-month`, `this-quarter`, `this-
    year`, `yesterday`, `last-week`, `last-month`, `last-quarter`, `last-year`, and `all-time`. Either this field or
    `cohort_datetime_range` needs to be specified for `created-cohort` reports. Its value will be ignored for `active-stage-
    cohort` reports.
    * `cohort_datetime_range`: a time range defining the cohort of created opportunities to fetch data for, by date of
    creation of those opportunities. Either this field or `cohort_relative_range` needs to be specified for `created-cohort`
    reports. Its value will be ignored for `active-stage-cohort` reports.
    * `compared_relative_range`: a relative time range to fetch comparison data for. Only allowed in combination with
    `report_relative_range` (for `active-stage-cohort` reports) or `cohort_relative_range` (for `created-cohort` reports).
    The allowed values are: `today`, `this-week`, `this-month`, `this-quarter`, `this-year`, `yesterday`, `last-week`,
    `last-month`, `last-quarter`, `last-year`, and `all-time`.
    * `compared_datetime_range`: a relative time range to fetch comparison data for. Only allowed in combination with
    `report_datetime_range` (for `active-stage-cohort` reports) or `cohort_datetime_range` (for `created-cohort` reports).
    The allowed values are: `same-days-last-week`, `same-days-last-month`, `same-days-last-quarter`, `same-days-last-year`.
    * `compared_custom_range`: a time range to fetch comparison data for.
    * `query`: a query to apply to the report to filter out data.
      The value of the field is a dictionary with the key `type` and any type-specific keys. For now only the type
    `saved_search` is allowed which takes the extra key `saved_search_id` to specify the ID of a saved search. This
    parameter is *optional*.
    * `users`: a list of user IDs or group IDs to limit the report results to. When it's empty, the report will include all
    the available users. This parameter is *optional*.

    The report can be requested either in JSON format or in CSV format. The format can be specified with the `accept`
    header.

    In JSON format, it includes aggregated and per-user data. When requested in CSV format, it includes only per-user data.

    When `compared_datetime_range`, `compared_relative_range`, or `compared_custom_range` are used, the report returned is
    the compared one, not the base one.
    '''
    # handler for reporting_get_funnel_totals: POST /report/funnel/opportunity/totals/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "report/funnel/opportunity/totals/")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("POST", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)


if __name__ == "__main__":
    app()
