#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated

import typer
from rich_objects import display

from close_cli import _arguments as _a
from close_cli import _display as _d  # noqa: F401
from close_cli import _exceptions as _e
from close_cli import _logging as _l
from close_cli import _requests as _r
from close_cli import _tree as _t

app = typer.Typer(no_args_is_help=True, help="Manage report statuses")


@app.command("commands", short_help="Display commands tree for statuses sub-commands")
def show_commands(
    display_opt: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show statuses sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "report_statuses", display_opt, depth, search)


@app.command("lead", short_help="Get lead status change report")
def reporting_get_lead_statuses(
    org_id: Annotated[str, typer.Argument(show_default=False)],
    date_start: Annotated[str | None, typer.Option(show_default=False)] = None,
    date_end: Annotated[str | None, typer.Option(show_default=False)] = None,
    query: Annotated[str | None, typer.Option(show_default=False)] = None,
    smart_view_id: Annotated[str | None, typer.Option(show_default=False)] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Get a lead status change report.

    The date range is optional. A report may be requested
    for a specific time period or overall. You can specify
    either a `query` or `smart_view_id` (but not both) to
    filter leads included in the report.

    The following fields are returned (when requesting an
    overall report, some inapplicable fields will not be
    returned):

    * `status_overview`: A list of all statuses with:
        * `status_id`, `status_label`,
          `status_is_deleted`: The ID and label of the
          status, and whether it was deleted.
        * `started`: Number of leads in this status at
          the start of the period.
        * `ended`: Number in this status at the end.
        * `change`: Net change during the period
          (`ended` minus `started`).
        * `change_percent`: Net change in percent.
        * `gained`: Number that were not in this status
          at the beginning but were at the end.
        * `lost`: Number that were in this status at the
          beginning but were not at the end.
        * `entered`: Number that entered this status at
          some point during the period.
        * `left`: Number that left this status at some
          point during the period.
        * `_queries`: A dictionary containing search
          queries for the different states (`started`,
          `ended`, `gained`, `lost`, `entered`, `left`).
        * `_leads_page_urls`: A dictionary containing
          paths to the lead search UI page.
    * `status_transitions`: A list of all status
      transitions (aggregated by start/end status) for
      the given period with:
        * `from_status_id`, `from_status_label`,
          `from_status_is_deleted`: Starting status
          (null for created leads).
        * `to_status_id`, `to_status_label`,
          `to_status_is_deleted`: Ending status.
        * `count`: The number that transitioned.
        * `_query`: The search query for those records.
        * `_leads_page_url`: Path to the search UI page.
    * `status_transitions_summary`: Status transitions
      summarized for the period. E.g. a lead that went
      A→B→C is counted as A→C.
    '''
    # handler for reporting_get_lead_statuses: GET /report/statuses/lead/{org_id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "report/statuses/lead", org_id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if date_start is not None:
        params["date_start"] = date_start
    if date_end is not None:
        params["date_end"] = date_end
    if query is not None:
        params["query"] = query
    if smart_view_id is not None:
        params["smart_view_id"] = smart_view_id

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)


@app.command("opportunity", short_help="Get opportunity status change report")
def reporting_get_opportunity_statuses(
    org_id: Annotated[str, typer.Argument(show_default=False)],
    date_start: Annotated[str | None, typer.Option(show_default=False)] = None,
    date_end: Annotated[str | None, typer.Option(show_default=False)] = None,
    query: Annotated[str | None, typer.Option(show_default=False)] = None,
    smart_view_id: Annotated[str | None, typer.Option(show_default=False)] = None,
    user_id: Annotated[str | None, typer.Option(show_default=False)] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Get an opportunity status change report.

    The date range is optional. A report may be requested
    for a specific time period or overall. You can specify
    either a `query` or `smart_view_id` (but not both) to
    filter opportunities included in the report. The
    report may optionally be filtered by the opportunity
    user.

    The following fields are returned (when requesting an
    overall report, some inapplicable fields will not be
    returned):

    * `status_overview`: A list of all statuses with:
        * `status_id`, `status_label`,
          `status_is_deleted`: The ID and label of the
          status, and whether it was deleted.
        * `started`: Number of opportunities in this
          status at the start of the period.
        * `ended`: Number in this status at the end.
        * `change`: Net change during the period
          (`ended` minus `started`).
        * `change_percent`: Net change in percent.
        * `gained`: Number that were not in this status
          at the beginning but were at the end.
        * `lost`: Number that were in this status at the
          beginning but were not at the end.
        * `entered`: Number that entered this status at
          some point during the period.
        * `left`: Number that left this status at some
          point during the period.
        * `_queries`: A dictionary containing search
          queries for the different states (`started`,
          `ended`, `gained`, `lost`, `entered`, `left`).
          Search queries are wrapped in a nested
          `opportunity(...)` clause. To pass the query
          to the opportunities API endpoint, use only
          the query within the parentheses.
        * `_leads_page_urls`: A dictionary containing
          paths to the lead search UI page.
        * `_opportunities_page_urls`: A dictionary
          containing paths to the opportunity UI page.
    * `status_transitions`: A list of all status
      transitions (aggregated by start/end status) for
      the given period with:
        * `from_status_id`, `from_status_label`,
          `from_status_is_deleted`: Starting status
          (null for created opportunities).
        * `to_status_id`, `to_status_label`,
          `to_status_is_deleted`: Ending status.
        * `count`: The number that transitioned.
        * `_query`: The search query for those records.
        * `_leads_page_url`: Path to the search UI page.
        * `_opportunities_page_url`: Path to the
          opportunity UI page.
    * `status_transitions_summary`: Status transitions
      summarized for the period. E.g. an opportunity
      that went A→B→C is counted as A→C.
    '''
    # handler for reporting_get_opportunity_statuses: GET /report/statuses/opportunity/{org_id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "report/statuses/opportunity", org_id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    if date_start is not None:
        params["date_start"] = date_start
    if date_end is not None:
        params["date_end"] = date_end
    if query is not None:
        params["query"] = query
    if smart_view_id is not None:
        params["smart_view_id"] = smart_view_id
    if user_id is not None:
        params["user_id"] = user_id

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)


if __name__ == "__main__":
    app()
