#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated

import typer
from rich_objects import display

from close_cli import _arguments as _a
from close_cli import _display as _d  # noqa: F401
from close_cli import _exceptions as _e
from close_cli import _logging as _l
from close_cli import _requests as _r
from close_cli import _tree as _t
from close_cli.scheduling_link_integration import app as scheduling_link_integration

app = typer.Typer(no_args_is_help=True, help="Manage scheduling-link")
app.add_typer(scheduling_link_integration, name="integration")


@app.command("commands", short_help="Display commands tree for scheduling-link sub-commands")
def show_commands(
    display_opt: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show scheduling-link sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "scheduling_link", display_opt, depth, search)


@app.command("create", short_help="Create a User Scheduling Link")
def scheduling_links_create(
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Create a User Scheduling Link
    '''
    # handler for scheduling_links_create: POST /scheduling_link/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "scheduling_link/")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("POST", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:  # noqa: BLE001
        _e.handle_exceptions(ex)


@app.command("delete", short_help="Delete a User Scheduling Link")
def scheduling_links_delete(
    id: Annotated[str, typer.Argument(show_default=False)],
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Delete a User Scheduling Link
    '''
    # handler for scheduling_links_delete: DELETE /scheduling_link/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "scheduling_link", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("DELETE", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:  # noqa: BLE001
        _e.handle_exceptions(ex)


@app.command("list", short_help="List User Scheduling Links")
def scheduling_links_list(
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    List User Scheduling Links
    '''
    # handler for scheduling_links_list: GET /scheduling_link/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "scheduling_link/")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:  # noqa: BLE001
        _e.handle_exceptions(ex)


@app.command("set", short_help="Update a User Scheduling Link")
def scheduling_links_update(
    id: Annotated[str, typer.Argument(show_default=False)],
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Update a User Scheduling Link
    '''
    # handler for scheduling_links_update: PUT /scheduling_link/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "scheduling_link", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("PUT", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:  # noqa: BLE001
        _e.handle_exceptions(ex)


@app.command("show", short_help="Fetch a User Scheduling Link")
def scheduling_links_get(
    id: Annotated[str, typer.Argument(show_default=False)],
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Fetch a User Scheduling Link
    '''
    # handler for scheduling_links_get: GET /scheduling_link/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "scheduling_link", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:  # noqa: BLE001
        _e.handle_exceptions(ex)


if __name__ == "__main__":
    app()
