#!/usr/bin/env python3
# Copyright 2026
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Annotated  # noqa: F401

import typer
from rich_objects import display  # noqa: F401

from close_cli import _arguments as _a
from close_cli import _display as _d  # noqa: F401
from close_cli import _exceptions as _e  # noqa: F401
from close_cli import _logging as _l  # noqa: F401
from close_cli import _requests as _r  # noqa: F401
from close_cli import _tree as _t

app = typer.Typer(no_args_is_help=True, help="Manage webhook")


@app.command("commands", short_help="Display commands tree for webhook sub-commands")
def show_commands(
    display_opt: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
    search: _a.TreeSearchOption = None,
) -> None:
    """Show webhook sub-commands.

    The '*' denotes a sub-command with other sub-commands, but no direct actions.
    """
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "webhook", display_opt, depth, search)


@app.command("create", short_help="Create new Webhook subscription")
def webhooks_create(
    events_action: Annotated[str, typer.Option(show_default=False)] = None,
    events_object_type: Annotated[str, typer.Option(show_default=False)] = None,
    url: Annotated[str, typer.Option(show_default=False, help="Destination URL for the webhook subscription")] = None,
    verify_ssl: Annotated[bool | None, typer.Option("--verify-ssl/--no-verify-ssl", help="Verify SSL certificate of destination webhook URL. Set to `false` to disable SSL certificate validation. We recommend using https to protect your data during delivery.")] = True,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    The subscription will send events to the specified URL.
    '''
    # handler for webhooks_create: POST /webhook/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "webhook/")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if events_action is None:
        missing.append("--events-action")
    if events_object_type is None:
        missing.append("--events-object-type")
    if url is None:
        missing.append("--url")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    body = {}
    events = {}
    events["action"] = events_action
    events["object_type"] = events_object_type
    body["url"] = url
    if verify_ssl is not None:
        body["verify_ssl"] = verify_ssl
    # stitch together the sub-objects
    if events:
        body["events"] = [events]  # convert to list

    try:
        data = _r.request("POST", url, headers=headers, params=params, body=body, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)


@app.command("delete", short_help="Delete Webhook subscription")
def webhooks_delete(
    id: Annotated[str, typer.Argument(show_default=False)],
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Delete Webhook subscription
    '''
    # handler for webhooks_delete: DELETE /webhook/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "webhook", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("DELETE", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)


@app.command("list", short_help="List Webhook subscriptions")
def webhooks_list(
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    List all webhook subscriptions for the organization.
    '''
    # handler for webhooks_list: GET /webhook/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "webhook/")
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)


class WebhookStatus(str, Enum):  # noqa: F811
    ACTIVE = "active"
    PAUSED = "paused"


@app.command("set", short_help="Update existing Webhook subscription")
def webhooks_update(
    id: Annotated[str, typer.Argument(show_default=False)],
    status: Annotated[WebhookStatus | None, typer.Option(show_default=False, case_sensitive=False)] = None,
    url: Annotated[str | None, typer.Option(show_default=False, help="Destination URL for the webhook subscription")] = None,
    verify_ssl: Annotated[bool | None, typer.Option("--verify-ssl/--no-verify-ssl", show_default=False, help="Verify SSL certificate of destination webhook URL. Set to `false` to disable SSL certificate validation. We recommend using https to protect your data during delivery.")] = None,
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    Update existing Webhook subscription
    '''
    # handler for webhooks_update: PUT /webhook/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "webhook", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}
    body = {}
    if status is not None:
        body["status"] = status
    if url is not None:
        body["url"] = url
    if verify_ssl is not None:
        body["verify_ssl"] = verify_ssl

    try:
        data = _r.request("PUT", url, headers=headers, params=params, body=body, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)


@app.command("show", short_help="Retrieve a single Webhook subscription")
def webhooks_get(
    id: Annotated[str, typer.Argument(show_default=False)],
    _api_host: _a.ApiHostOption = "https://api.close.com/api/v1",
    _api_key: _a.ApiKeyOption = None,
    _api_timeout: _a.ApiTimeoutOption = 5,
    _log_level: _a.LogLevelOption = _a.LogLevel.WARN,
    _out_fmt: _a.OutputFormatOption = _a.OutputFormat.TABLE,
    _out_style: _a.OutputStyleOption = _a.OutputStyle.ALL,
) -> None:
    '''
    The response contains the subscription details.
    '''
    # handler for webhooks_get: GET /webhook/{id}/
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "webhook", id)
    missing = []
    if _api_key is None:
        missing.append("--api-key")
    if missing:
        _e.handle_exceptions(_e.MissingRequiredError(missing))

    params = {}

    try:
        data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
        display(data, _out_fmt, _out_style)
    except Exception as ex:
        _e.handle_exceptions(ex)


if __name__ == "__main__":
    app()
