COMPONENTS = "components"
NAME = "name"
NULLABLE = "nullable"
OP_ID = "operationId"
PARAMS = "parameters"
PATHS = "paths"
PROPS = "properties"
REFS = "$ref"
REQUIRED = "required"
SCHEMAS = "schemas"
TAGS = "tags"

X_METHOD = "x-method"
X_PATH = "x-path"
X_PATH_PARAMS = "x-path-params"
