# Copyright 2025
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#
import logging

import pytest

from pets_cli._logging import LOG_CLASS
from pets_cli._logging import LogLevel
from pets_cli._logging import init_logging
from pets_cli._logging import logger


def test_get_logger() -> None:
    log = logger()
    assert log.name == LOG_CLASS

    req_logger = logger("requests")
    assert req_logger.name == "requests"


@pytest.mark.parametrize(
    ["level", "expected"],
    [
        pytest.param(LogLevel.CRITICAL, logging.CRITICAL, id="critical"),
        pytest.param(LogLevel.ERROR, logging.ERROR, id="error"),
        pytest.param(LogLevel.WARN, logging.WARN, id="warn"),
        pytest.param(LogLevel.INFO, logging.INFO, id="info"),
        pytest.param(LogLevel.DEBUG, logging.DEBUG, id="debug"),
    ]
)
def test_init_logging(level: LogLevel, expected: int) -> None:
    init_logging(level)
    log = logger()
    assert LOG_CLASS == log.name
    assert expected == log.level
