# Copyright 2025
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from typing import Any
from typing import Optional  # noqa: F401

from pets_api import _environment as _e  # noqa: F401
from pets_api import _logging as _l  # noqa: F401
from pets_api import _requests as _r  # noqa: F401


def list_pets(
    limit: Optional[int] = None,  # How many items to return at one time (max 100)
    _api_host: str = _e.env_str("API_HOST", "http://petstore.swagger.io/v1"),  # host URL
    _api_key: str = _e.env_str("API_KEY"),  # API key for bearer authentication
    _api_timeout: int = _e.env("API_TIMEOUT", 5),  # timeout for operation
    _log_level: str = _e.env("API_LOG_LEVEL", "info"),  # log level
) -> Any:
    '''
    List all pets
    '''
    # handler for listPets: GET /pets
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "pets")

    params = {}
    if limit is not None:
        params["limit"] = limit

    data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
    return data


def create_pets(
    id: int = None,
    name: str = None,
    tag: Optional[str] = None,
    owner: str = None,
    _api_host: str = _e.env_str("API_HOST", "http://petstore.swagger.io/v1"),  # host URL
    _api_key: str = _e.env_str("API_KEY"),  # API key for bearer authentication
    _api_timeout: int = _e.env("API_TIMEOUT", 5),  # timeout for operation
    _log_level: str = _e.env("API_LOG_LEVEL", "info"),  # log level
) -> Any:
    '''
    Create a pet
    '''
    # handler for createPets: POST /pets
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key, content_type="application/json")
    url = _r.create_url(_api_host, "pets")

    params = {}
    body = {}
    body["id"] = id
    body["name"] = name
    if tag is not None:
        body["tag"] = tag
    body["owner"] = owner

    data = _r.request("POST", url, headers=headers, params=params, body=body, timeout=_api_timeout)
    return data


def show_pet_by_id(
    pet_id: str,  # The id of the pet to retrieve
    _api_host: str = _e.env_str("API_HOST", "http://petstore.swagger.io/v1"),  # host URL
    _api_key: str = _e.env_str("API_KEY"),  # API key for bearer authentication
    _api_timeout: int = _e.env("API_TIMEOUT", 5),  # timeout for operation
    _log_level: str = _e.env("API_LOG_LEVEL", "info"),  # log level
) -> Any:
    '''
    Info for a specific pet
    '''
    # handler for showPetById: GET /pets/{petId}
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "pets", pet_id)

    params = {}

    data = _r.request("GET", url, headers=headers, params=params, timeout=_api_timeout)
    return data


def delete_pet_by_id(
    pet_id: str,  # The id of the pet to retrieve
    _api_host: str = _e.env_str("API_HOST", "http://petstore.swagger.io/v1"),  # host URL
    _api_key: str = _e.env_str("API_KEY"),  # API key for bearer authentication
    _api_timeout: int = _e.env("API_TIMEOUT", 5),  # timeout for operation
    _log_level: str = _e.env("API_LOG_LEVEL", "info"),  # log level
) -> Any:
    '''
    Delete a pet
    '''
    # handler for deletePetById: DELETE /pets/{petId}
    _l.init_logging(_log_level)
    headers = _r.request_headers(_api_key)
    url = _r.create_url(_api_host, "pets", pet_id)

    params = {}

    data = _r.request("DELETE", url, headers=headers, params=params, timeout=_api_timeout)
    return data
