from datetime import datetime
from typing import Any

from oas_tools.cli_gen.layout_types import CommandNode
from oas_tools.cli_gen.utils import to_snake_case
from oas_tools.types import OasField
from oas_tools.utils import map_operations

NL = "\n"

class Generator:
    def __init__(self, package_name: str, oas: dict[str, Any]):
        self.package_name = package_name
        self.operations = map_operations(oas.get(OasField.PATHS, {}))
        self.models = oas.get(OasField.COMPONENTS, {}).get(OasField.SCHEMAS, {})

    def shebang(self) -> str:
        """Returns the shebang line that goes at the top of each file."""
        return f"#!/usr/bin/env python3{NL}"

    def copyright(self) -> str:
        """Returns the copyright header near the top of each file."""
        return f"""\
# Copyright {datetime.now().year}
#
# This code was generated by the oas-tools CLI generator.
#
"""

    def standard_imports(self) -> str:
        return """
from enum import Enum
from typing_extensions import Annotated

import typer

"""

    def subcommand_imports(self, subcommands: list[CommandNode]) -> str:
        return NL.join(
            f"from {self.package_name}.{to_snake_case(n.identifier)} import app as {to_snake_case(n.identifier)}"
            for n in subcommands
        )

    def app_definition(self, node: CommandNode) -> str:
        result = f"""

app = typer.Typer(help="{node.description}")
"""
        for child in node.subcommands():
            result += f"""\
app.add_typer({to_snake_case(child.identifier)}, name="{child.command}")
"""

        return result

    def main(self) -> str:
        return """

if __name__ == "__main__":
    app()
"""

    def op_short_help(self, operation: dict[str, Any]) -> str:
        """Gets the short help for the operation."""
        summary = operation.get(OasField.SUMMARY)
        if summary:
            return summary

        description = operation.get(OasField.DESCRIPTION, "")
        return description.split(". ")[0]

    def op_long_help(self, operation: dict[str, Any]) -> str:
        text = operation.get(OasField.DESCRIPTION) or operation.get(OasField.SUMMARY) or ""
        # TODO: sanitize  NL's, long text, etc
        return text

    def function_definition(self, node: CommandNode) -> str:
        op = self.operations.get(node.identifier)
        method = op.get(OasField.X_METHOD).upper()

        return f"""

@app.command("{node.command}", help="{self.op_short_help(op)}")
def {to_snake_case(node.identifier)}() -> None:
    '''
    {self.op_long_help(op)}
    '''
    # handler for {node.identifier}: {method} {op.get(OasField.X_PATH)}
    return
"""
