#!/usr/bin/env python3
# Copyright 2025
#
# This code was generated by the openapi-spec-tools CLI generator, DO NOT EDIT
#

from datetime import date  # noqa: F401
from datetime import datetime  # noqa: F401
from enum import Enum  # noqa: F401
from pathlib import Path
from typing import Optional
from typing_extensions import Annotated

import typer

from github_gen_cli import _arguments as _a
from github_gen_cli import _display as _d
from github_gen_cli import _exceptions as _e
from github_gen_cli import _logging as _l
from github_gen_cli import _requests as _r
from github_gen_cli import _tree as _t
from github_gen_cli.users import app as users

app = typer.Typer(no_args_is_help=True, help="Generated GitHub CLI from OAS")
app.add_typer(users, name="users")

@app.command("commands", short_help="Display commands tree for sub-commands")
def show_commands(
    display: _a.TreeDisplayOption = _a.TreeDisplay.HELP,
    depth: _a.MaxDepthOption = 5,
) -> None:
    path = Path(__file__).parent / "tree.yaml"
    _t.tree(path.as_posix(), "main", display, depth)
    return


if __name__ == "__main__":
    app()
